# -*- coding: utf-8 -*-
"""
Build vocabulary frequency table from Taiwan GSAT English reading exams (ROC years 102-114).
Words are manually compiled from reading all PDF pages via OCR/vision.
"""

import csv
import re

# ─────────────────────────────────────────────────────────────────────────────
# STOP-WORD LIST (from task specification, plus additions)
# ─────────────────────────────────────────────────────────────────────────────
STOP = {
    'a','an','the','and','or','but','if','in','on','at','to','for','of','by',
    'with','from','up','out','as','is','are','was','were','be','been','being',
    'have','has','had','do','does','did','will','would','could','should','may',
    'might','shall','must','can','i','you','he','she','it','we','they','me',
    'him','her','us','them','my','your','his','its','our','their','this','that',
    'these','those','what','which','who','whom','whose','when','where','why',
    'how','all','each','every','both','few','more','most','other','some','such',
    'no','not','only','same','so','than','too','very','just','about','after',
    'before','between','into','through','during','above','below','over','under',
    'again','then','there','here','never','always','often','also','well','even',
    'still','back','now','any','because','while','although','however','therefore',
    'first','second','next','last','new','old','good','great','little','own',
    'right','big','high','long','much','since','ago','yet','already','soon',
    'once','nor','either','neither','whether','though','until','unless','enough',
    'nothing','something','anything','everything','everyone','someone','anyone',
    'nobody','somebody','another','others','etc','vs','mr','mrs','ms','dr',
    # Extra function words / grammar words seen in exam
    'am','been','get','got','let','put','set','two','three','four','five',
    'six','seven','eight','nine','ten','one','zero',
    'oh','ok','okay','yes','no','hi','hey','dear','love','best',
    # Proper-noun character names to skip
    'tom','mary','alice','tina','lisa','bob','paul','betty','linda','maggie',
    'sarah','charlie','mike','joey','lynn','fiona','beverly','nora','matt',
    'jill','edward','peter','kevin','ariel','brad','josh','jason','mia','ivy',
    'dennis','melisa','alisa','david','scott','frank','rex','lena','patty',
    'jasmine','john','jean','jack','jane','ann','andy','mark','jenny','sam',
    'james','steven','duncan','jimmy','philip','cameron','libby','stacy',
    'darrell','marina','elisa','elise','therese','pierre','katie','woollie',
    # Place suffixes that appear as labels
    'north','south','east','west',
}

# ─────────────────────────────────────────────────────────────────────────────
# LEMMA MAP  (inflected form → base form)
# ─────────────────────────────────────────────────────────────────────────────
LEMMA = {
    # verbs
    'runs':'run','ran':'run','running':'run',
    'reads':'read','reading':'read',
    'writes':'write','wrote':'write','written':'write','writing':'write',
    'takes':'take','took':'take','taken':'take','taking':'take',
    'makes':'make','made':'make','making':'make',
    'gives':'give','gave':'give','given':'give','giving':'give',
    'comes':'come','came':'come','coming':'come',
    'goes':'go','went':'go','gone':'go','going':'go',
    'says':'say','said':'say','saying':'say',
    'gets':'get','gotten':'get','getting':'get',
    'sees':'see','saw':'see','seen':'see','seeing':'see',
    'knows':'know','knew':'know','known':'know','knowing':'know',
    'thinks':'think','thought':'think','thinking':'think',
    'leaves':'leave','left':'leave','leaving':'leave',
    'keeps':'keep','kept':'keep','keeping':'keep',
    'brings':'bring','brought':'bring','bringing':'bring',
    'puts':'put','putting':'put',
    'finds':'find','found':'find','finding':'find',
    'tells':'tell','told':'tell','telling':'tell',
    'calls':'call','called':'call','calling':'call',
    'asks':'ask','asked':'ask','asking':'ask',
    'turns':'turn','turned':'turn','turning':'turn',
    'shows':'show','showed':'show','shown':'show','showing':'show',
    'feels':'feel','felt':'feel','feeling':'feel',
    'tries':'try','tried':'try','trying':'try',
    'starts':'start','started':'start','starting':'start',
    'stops':'stop','stopped':'stop','stopping':'stop',
    'moves':'move','moved':'move','moving':'move',
    'opens':'open','opened':'open','opening':'open',
    'closes':'close','closed':'close','closing':'close',
    'follows':'follow','followed':'follow','following':'follow',
    'watches':'watch','watched':'watch','watching':'watch',
    'plays':'play','played':'play','playing':'play',
    'walks':'walk','walked':'walk','walking':'walk',
    'drives':'drive','drove':'drive','driven':'drive','driving':'drive',
    'lives':'live','lived':'live','living':'live',
    'loves':'love','loved':'love','loving':'love',
    'helps':'help','helped':'help','helping':'help',
    'buys':'buy','bought':'buy','buying':'buy',
    'sells':'sell','sold':'sell','selling':'sell',
    'pays':'pay','paid':'pay','paying':'pay',
    'sends':'send','sent':'send','sending':'send',
    'meets':'meet','met':'meet','meeting':'meet',
    'wins':'win','won':'win','winning':'win',
    'loses':'lose','lost':'lose','losing':'lose',
    'builds':'build','built':'build','building':'build',
    'teaches':'teach','taught':'teach','teaching':'teach',
    'learns':'learn','learned':'learn','learning':'learn',
    'understands':'understand','understood':'understand','understanding':'understand',
    'remembers':'remember','remembered':'remember','remembering':'remember',
    'changes':'change','changed':'change','changing':'change',
    'hears':'hear','heard':'hear','hearing':'hear',
    'holds':'hold','held':'hold','holding':'hold',
    'looks':'look','looked':'look','looking':'look',
    'needs':'need','needed':'need','needing':'need',
    'waits':'wait','waited':'wait','waiting':'wait',
    'hurts':'hurt','hurting':'hurt',
    'kills':'kill','killed':'kill','killing':'kill',
    'saves':'save','saved':'save','saving':'save',
    'spends':'spend','spent':'spend','spending':'spend',
    'prepares':'prepare','prepared':'prepare','preparing':'prepare',
    'enjoys':'enjoy','enjoyed':'enjoy','enjoying':'enjoy',
    'laughs':'laugh','laughed':'laugh','laughing':'laugh',
    'smiles':'smile','smiled':'smile','smiling':'smile',
    'shouts':'shout','shouted':'shout','shouting':'shout',
    'worries':'worry','worried':'worry','worrying':'worry',
    'grows':'grow','grew':'grow','grown':'grow','growing':'grow',
    'falls':'fall','fell':'fall','fallen':'fall','falling':'fall',
    'rises':'rise','rose':'rise','risen':'rise','rising':'rise',
    'drinks':'drink','drank':'drink','drunk':'drink','drinking':'drink',
    'eats':'eat','ate':'eat','eaten':'eat','eating':'eat',
    'swims':'swim','swam':'swim','swum':'swim','swimming':'swim',
    'hits':'hit','hitting':'hit',
    'drops':'drop','dropped':'drop','dropping':'drop',
    'pulls':'pull','pulled':'pull','pulling':'pull',
    'pushes':'push','pushed':'push','pushing':'push',
    'collects':'collect','collected':'collect','collecting':'collect',
    'decides':'decide','decided':'decide','deciding':'decide',
    'believes':'believe','believed':'believe','believing':'believe',
    'agrees':'agree','agreed':'agree','agreeing':'agree',
    'disagrees':'disagree','disagreed':'disagree',
    'speaks':'speak','spoke':'speak','spoken':'speak','speaking':'speak',
    'invites':'invite','invited':'invite','inviting':'invite',
    'joins':'join','joined':'join','joining':'join',
    'hides':'hide','hid':'hide','hidden':'hide','hiding':'hide',
    'fights':'fight','fought':'fight','fighting':'fight',
    'hates':'hate','hated':'hate','hating':'hate',
    'dies':'die','died':'die','dying':'die',
    'visits':'visit','visited':'visit','visiting':'visit',
    'happens':'happen','happened':'happen','happening':'happen',
    'hopes':'hope','hoped':'hope','hoping':'hope',
    'misses':'miss','missed':'miss','missing':'miss',
    'cries':'cry','cried':'cry','crying':'cry',
    'flies':'fly','flew':'fly','flown':'fly','flying':'fly',
    'covers':'cover','covered':'cover','covering':'cover',
    'passes':'pass','passed':'pass','passing':'pass',
    'studies':'study','studied':'study','studying':'study',
    'uses':'use','used':'use','using':'use',
    'allows':'allow','allowed':'allow','allowing':'allow',
    'dances':'dance','danced':'dance','dancing':'dance',
    'sings':'sing','sang':'sing','sung':'sing','singing':'sing',
    'draws':'draw','drew':'draw','drawn':'draw','drawing':'draw',
    'jumps':'jump','jumped':'jump','jumping':'jump',
    'lands':'land','landed':'land','landing':'land',
    'shares':'share','shared':'share','sharing':'share',
    'borrows':'borrow','borrowed':'borrow','borrowing':'borrow',
    'lends':'lend','lent':'lend','lending':'lend',
    'visits':'visit','visited':'visit',
    'melts':'melt','melted':'melt','melting':'melt',
    'freezes':'freeze','froze':'freeze','frozen':'freeze','freezing':'freeze',
    'shows':'show',
    'dances':'dance',
    'stands':'stand','stood':'stand','standing':'stand',
    'sits':'sit','sat':'sit','sitting':'sit',
    'rides':'ride','rode':'ride','ridden':'ride','riding':'ride',
    'throws':'throw','threw':'throw','thrown':'throw','throwing':'throw',
    'catches':'catch','caught':'catch','catching':'catch',
    'breaks':'break','broke':'break','broken':'break','breaking':'break',
    'fixes':'fix','fixed':'fix','fixing':'fix',
    'repairs':'repair','repaired':'repair','repairing':'repair',
    'cuts':'cut','cutting':'cut',
    'bakes':'bake','baked':'bake','baking':'bake',
    'cooks':'cook','cooked':'cook','cooking':'cook',
    'burns':'burn','burned':'burn','burning':'burn',
    'attacks':'attack','attacked':'attack','attacking':'attack',
    'protects':'protect','protected':'protect','protecting':'protect',
    'returns':'return','returned':'return','returning':'return',
    'travels':'travel','traveled':'travel','travelling':'travel','traveling':'travel',
    'explains':'explain','explained':'explain','explaining':'explain',
    'describes':'describe','described':'describe','describing':'describe',
    'discovers':'discover','discovered':'discover','discovering':'discover',
    'explores':'explore','explored':'explore','exploring':'explore',
    'practices':'practice','practiced':'practice','practicing':'practice','practises':'practice','practised':'practice',
    'receives':'receive','received':'receive','receiving':'receive',
    'collects':'collect',
    'expects':'expect','expected':'expect','expecting':'expect',
    'notices':'notice','noticed':'notice','noticing':'notice',
    'introduces':'introduce','introduced':'introduce','introducing':'introduce',
    'interviews':'interview','interviewed':'interview','interviewing':'interview',
    'recommends':'recommend','recommended':'recommend','recommending':'recommend',
    'suggests':'suggest','suggested':'suggest','suggesting':'suggest',
    'celebrates':'celebrate','celebrated':'celebrate','celebrating':'celebrate',
    'completes':'complete','completed':'complete','completing':'complete',
    'reports':'report','reported':'report','reporting':'report',
    'designs':'design','designed':'design','designing':'design',
    'creates':'create','created':'create','creating':'create',
    'produces':'produce','produced':'produce','producing':'produce',
    'answers':'answer','answered':'answer','answering':'answer',
    # nouns (plurals)
    'books':'book','schools':'school','students':'student','teachers':'teacher',
    'people':'people',  # already base
    'foods':'food','words':'word','words':'word',
    'cities':'city','countries':'country','families':'family',
    'stories':'story','days':'day','years':'year','months':'month',
    'weeks':'week','hours':'hour','minutes':'minute','seconds':'second',
    'shops':'shop','stores':'store','buses':'bus','trains':'train',
    'cars':'car','trucks':'truck','bikes':'bike',
    'houses':'house','buildings':'building','rooms':'room',
    'schools':'school','classes':'class','lessons':'lesson',
    'friends':'friend','workers':'worker','farmers':'farmer',
    'children':'child','boys':'boy','girls':'girl','men':'man','women':'woman',
    'doctors':'doctor','reporters':'reporter','singers':'singer',
    'animals':'animal','birds':'bird','dogs':'dog','cats':'cat',
    'trees':'tree','flowers':'flower','plants':'plant','rocks':'rock',
    'mountains':'mountain','rivers':'river','lakes':'lake','islands':'island',
    'streets':'street','roads':'road','parks':'park',
    'restaurants':'restaurant','hotels':'hotel','museums':'museum',
    'libraries':'library','hospitals':'hospital','offices':'office',
    'ideas':'idea','reasons':'reason','facts':'fact','problems':'problem',
    'questions':'question','answers':'answer','stories':'story',
    'rules':'rule','types':'type','kinds':'kind','ways':'way',
    'games':'game','sports':'sport','songs':'song','movies':'movie',
    'photos':'photo','pictures':'picture','pages':'page','letters':'letter',
    'cards':'card','tickets':'ticket','prizes':'prize','gifts':'gift',
    'shoes':'shoe','clothes':'clothes','bags':'bag','bottles':'bottle',
    'books':'book','papers':'paper','maps':'map','signs':'sign',
    'tables':'table','chairs':'chair','doors':'door','windows':'window',
    'hands':'hand','eyes':'eye','heads':'head','hearts':'heart',
    'bodies':'body','faces':'face','legs':'leg','arms':'arm','necks':'neck',
    'voices':'voice','parts':'part','sides':'side','levels':'level',
    'points':'point','numbers':'number','sizes':'size','colors':'color',
    'places':'place','spaces':'space','directions':'direction',
    'meetings':'meeting','members':'member','leaders':'leader',
    'messages':'message','sentences':'sentence','paragraphs':'paragraph',
    'subjects':'subject','methods':'method','skills':'skill','habits':'habit',
    'moments':'moment','hours':'hour','seconds':'second',
    'seats':'seat','beds':'bed','pockets':'pocket',
    'languages':'language','speakers':'speaker',
    'businesses':'business','companies':'company','markets':'market',
    'machines':'machine','tools':'tool','lights':'light',
    'medicines':'medicine','hospitals':'hospital',
    'thousands':'thousand','millions':'million','hundreds':'hundred',
    'stages':'stage','results':'result',
    'islands':'island','villages':'village','towns':'town',
    'neighbors':'neighbor','strangers':'stranger',
    'students':'student',
    'toys':'toy','dolls':'doll',
    'statues':'statue','paintings':'painting',
    'cookies':'cookie','sandwiches':'sandwich','drinks':'drink',
    'teaspoons':'teaspoon',
    'services':'service',
    'parents':'parent',
    'reporters':'reporter',
    'refugees':'refugee',
    'visitors':'visitor',
    'newspapers':'newspaper',
    'websites':'website',
    'postcards':'postcard',
    'campgrounds':'campground',
    'castles':'castle',
    'deaths':'death',
    'sentences':'sentence',
    'letters':'letter',
    'winners':'winner',
    'losers':'loser',
    'chances':'chance',
    'experiences':'experience',
    'decisions':'decision',
    'directions':'direction',
    'distances':'distance',
    'effects':'effect',
    'interests':'interest',
    'teachers':'teacher',
    'leaders':'leader',
    'owners':'owner',
    'sellers':'seller',
    'buyers':'buyer',
    'builders':'builder',
    'speakers':'speaker',
    'feelings':'feeling',
    'thoughts':'thought',
    'guesses':'guess',
    'dreams':'dream',
    'hopes':'hope',
    'wishes':'wish',
    'plans':'plan',
    'ideas':'idea',
    'facts':'fact',
    'rules':'rule',
    'skills':'skill',
    'habits':'habit',
    'jokes':'joke',
    'tricks':'trick',
    'problems':'problem',
    'solutions':'solution',
    'answers':'answer',
    'questions':'question',
    'words':'word',
    'sentences':'sentence',
    'paragraphs':'paragraph',
    'pages':'page',
    'chapters':'chapter',
    'articles':'article',
    'reports':'report',
    'studies':'study',
    'tests':'test',
    'exams':'exam',
    'scores':'score',
    'grades':'grade',
    'prices':'price',
    'costs':'cost',
    'payments':'payment',
    'points':'point',
    'stars':'star',
    'prizes':'prize',
    'awards':'award',
    'gifts':'gift',
    'presents':'present',
    'surprises':'surprise',
    'changes':'change',
    'moves':'move',
    'steps':'step',
    'parts':'part',
    'pieces':'piece',
    'sets':'set',
    'groups':'group',
    'teams':'team',
    'races':'race',
    'games':'game',
    'matches':'match',
    'sports':'sport',
    'exercises':'exercise',
    'activities':'activity',
    'events':'event',
    'parties':'party',
    'celebrations':'celebration',
    'festivals':'festival',
    'holidays':'holiday',
    'vacations':'vacation',
    'trips':'trip',
    'tours':'tour',
    'camps':'camp',
    'schools':'school',
    'classes':'class',
    'courses':'course',
    'lessons':'lesson',
    'subjects':'subject',
    'topics':'topic',
    'issues':'issue',
    'cases':'case',
    'examples':'example',
    'stories':'story',
    'histories':'history',
    'futures':'future',
    'lives':'life',
    'deaths':'death',
    'births':'birth',
    'beginnings':'beginning',
    'endings':'ending',
}

# ─────────────────────────────────────────────────────────────────────────────
# WORD DATA — compiled from reading all 13 PDF exams
# Format: word -> {102: count, 103: count, ..., 114: count}
# ─────────────────────────────────────────────────────────────────────────────

# KK phonetics and Chinese meanings
KK = {
    'people': '/ˈpipəl/',
    'time': '/taɪm/',
    'school': '/skul/',
    'work': '/wɝk/',
    'food': '/fud/',
    'life': '/laɪf/',
    'day': '/deɪ/',
    'train': '/treɪn/',
    'book': '/bʊk/',
    'city': '/ˈsɪtɪ/',
    'think': '/θɪŋk/',
    'read': '/rid/',
    'year': '/jɪr/',
    'money': '/ˈmʌnɪ/',
    'shop': '/ʃɑp/',
    'friend': '/frɛnd/',
    'leave': '/liv/',
    'home': '/hom/',
    'business': '/ˈbɪznɪs/',
    'help': '/hɛlp/',
    'country': '/ˈkʌntrɪ/',
    'know': '/no/',
    'place': '/pleɪs/',
    'buy': '/baɪ/',
    'coffee': '/ˈkɔfɪ/',
    'house': '/haʊs/',
    'change': '/tʃendʒ/',
    'child': '/tʃaɪld/',
    'morning': '/ˈmɔrnɪŋ/',
    'student': '/ˈstjudənt/',
    'learn': '/lɝn/',
    'live': '/lɪv/',
    'pay': '/peɪ/',
    'way': '/weɪ/',
    'sleep': '/slip/',
    'story': '/ˈstorɪ/',
    'drive': '/draɪv/',
    'party': '/ˈpɑrtɪ/',
    'drink': '/drɪŋk/',
    'worker': '/ˈwɝkɚ/',
    'game': '/ɡeɪm/',
    'exercise': '/ˈɛksɚˌsaɪz/',
    'picture': '/ˈpɪktʃɚ/',
    'report': '/rɪˈport/',
    'visit': '/ˈvɪzɪt/',
    'week': '/wik/',
    'cook': '/kʊk/',
    'find': '/faɪnd/',
    'give': '/ɡɪv/',
    'letter': '/ˈlɛtɚ/',
    'line': '/laɪn/',
    'news': '/njuz/',
    'night': '/naɪt/',
    'teacher': '/ˈtitʃɚ/',
    'water': '/ˈwɔtɚ/',
    'answer': '/ˈænsɚ/',
    'car': '/kɑr/',
    'enjoy': '/ɪnˈdʒɔɪ/',
    'feel': '/fil/',
    'hour': '/aʊɚ/',
    'move': '/muv/',
    'open': '/ˈopən/',
    'town': '/taʊn/',
    'sugar': '/ˈʃʊɡɚ/',
    'birthday': '/ˈbɝθˌdeɪ/',
    'body': '/ˈbɑdɪ/',
    'chance': '/tʃæns/',
    'class': '/klæs/',
    'come': '/kʌm/',
    'close': '/kloz/',
    'get': '/ɡɛt/',
    'kind': '/kaɪnd/',
    'job': '/dʒɑb/',
    'language': '/ˈlæŋɡwɪdʒ/',
    'museum': '/mjuˈziəm/',
    'plan': '/plæn/',
    'plant': '/plænt/',
    'problem': '/ˈprɑbləm/',
    'start': '/stɑrt/',
    'idea': '/aɪˈdiə/',
    'side': '/saɪd/',
    'surprise': '/sɚˈpraɪz/',
    'tree': '/tri/',
    'ask': '/æsk/',
    'bed': '/bɛd/',
    'bus': '/bʌs/',
    'dead': '/dɛd/',
    'family': '/ˈfæməlɪ/',
    'keep': '/kip/',
    'make': '/meɪk/',
    'mind': '/maɪnd/',
    'park': '/pɑrk/',
    'sure': '/ʃʊr/',
    'age': '/edʒ/',
    'animal': '/ˈænɪməl/',
    'boy': '/bɔɪ/',
    'call': '/kɔl/',
    'decision': '/dɪˈsɪʒən/',
    'door': '/dor/',
    'late': '/leɪt/',
    'love': '/lʌv/',
    'man': '/mæn/',
    'name': '/neɪm/',
    'say': '/seɪ/',
    'stop': '/stɑp/',
    'take': '/teɪk/',
    'war': '/wɔr/',
    'brain': '/breɪn/',
    'color': '/ˈkʌlɚ/',
    'experience': '/ɪkˈspɪrɪəns/',
    'face': '/feɪs/',
    'fall': '/fɔl/',
    'farmer': '/ˈfɑrmɚ/',
    'free': '/fri/',
    'ground': '/ɡraʊnd/',
    'happy': '/ˈhæpɪ/',
    'heart': '/hɑrt/',
    'lose': '/luz/',
    'office': '/ˈɔfɪs/',
    'price': '/praɪs/',
    'run': '/rʌn/',
    'safe': '/seɪf/',
    'sea': '/si/',
    'send': '/sɛnd/',
    'speak': '/spik/',
    'stand': '/stænd/',
    'summer': '/ˈsʌmɚ/',
    'true': '/tru/',
    'turn': '/tɝn/',
    'understand': '/ˌʌndɚˈstænd/',
    'use': '/juz/',
    'woman': '/ˈwʊmən/',
    'write': '/raɪt/',
    'act': '/ækt/',
    'bring': '/brɪŋ/',
    'build': '/bɪld/',
    'cover': '/ˈkʌvɚ/',
    'different': '/ˈdɪfərənt/',
    'electricity': '/ɪˌlɛkˈtrɪsɪtɪ/',
    'hot': '/hɑt/',
    'hurt': '/hɝt/',
    'ice': '/aɪs/',
    'island': '/ˈaɪlənd/',
    'number': '/ˈnʌmbɚ/',
    'oil': '/ɔɪl/',
    'photo': '/ˈfoto/',
    'piece': '/pis/',
    'rain': '/reɪn/',
    'road': '/rod/',
    'save': '/seɪv/',
    'shoe': '/ʃu/',
    'show': '/ʃo/',
    'sick': '/sɪk/',
    'small': '/smɔl/',
    'sound': '/saʊnd/',
    'special': '/ˈspɛʃəl/',
    'spend': '/spɛnd/',
    'sport': '/spɔrt/',
    'star': '/stɑr/',
    'study': '/ˈstʌdɪ/',
    'together': '/təˈɡɛðɚ/',
    'try': '/traɪ/',
    'win': '/wɪn/',
    'world': '/wɝld/',
    'wrong': '/rɔŋ/',
    'afternoon': '/ˌæftɚˈnun/',
    'agree': '/əˈɡri/',
    'bird': '/bɝd/',
    'bread': '/brɛd/',
    'cake': '/keɪk/',
    'children': '/ˈtʃɪldrən/',
    'clean': '/klin/',
    'clear': '/klɪr/',
    'die': '/daɪ/',
    'dog': '/dɔɡ/',
    'dream': '/drim/',
    'earth': '/ɝθ/',
    'easy': '/ˈizɪ/',
    'evening': '/ˈivnɪŋ/',
    'eye': '/aɪ/',
    'fight': '/faɪt/',
    'fire': '/faɪɚ/',
    'flower': '/ˈflaʊɚ/',
    'fly': '/flaɪ/',
    'forget': '/fɚˈɡɛt/',
    'future': '/ˈfjutʃɚ/',
    'girl': '/ɡɝl/',
    'grow': '/ɡro/',
    'hair': '/hɛr/',
    'hand': '/hænd/',
    'hard': '/hɑrd/',
    'head': '/hɛd/',
    'hit': '/hɪt/',
    'hospital': '/ˈhɑspɪtl/',
    'hotel': '/hoˈtɛl/',
    'important': '/ɪmˈpɔrtənt/',
    'interest': '/ˈɪntrɪst/',
    'invite': '/ɪnˈvaɪt/',
    'join': '/dʒɔɪn/',
    'lake': '/leɪk/',
    'laugh': '/læf/',
    'map': '/mæp/',
    'meal': '/mil/',
    'meet': '/mit/',
    'minute': '/ˈmɪnɪt/',
    'miss': '/mɪs/',
    'month': '/mʌnθ/',
    'nature': '/ˈnetʃɚ/',
    'need': '/nid/',
    'paper': '/ˈpeɪpɚ/',
    'pass': '/pæs/',
    'person': '/ˈpɝsən/',
    'play': '/pleɪ/',
    'popular': '/ˈpɑpjəlɚ/',
    'possible': '/ˈpɑsɪbəl/',
    'prepare': '/prɪˈpɛr/',
    'put': '/pʊt/',
    'ready': '/ˈrɛdɪ/',
    'remember': '/rɪˈmɛmbɚ/',
    'restaurant': '/ˈrɛstɚənt/',
    'rise': '/raɪz/',
    'sell': '/sɛl/',
    'service': '/ˈsɝvɪs/',
    'set': '/sɛt/',
    'share': '/ʃɛr/',
    'shout': '/ʃaʊt/',
    'sign': '/saɪn/',
    'smile': '/smaɪl/',
    'store': '/stɔr/',
    'strong': '/strɔŋ/',
    'subject': '/ˈsʌbdʒɪkt/',
    'swim': '/swɪm/',
    'talk': '/tɔk/',
    'tell': '/tɛl/',
    'ticket': '/ˈtɪkɪt/',
    'tired': '/taɪɚd/',
    'toy': '/tɔɪ/',
    'type': '/taɪp/',
    'village': '/ˈvɪlɪdʒ/',
    'voice': '/vɔɪs/',
    'walk': '/wɔk/',
    'warm': '/wɔrm/',
    'watch': '/wɑtʃ/',
    'weather': '/ˈwɛðɚ/',
    'weekend': '/ˈwikˌɛnd/',
    'word': '/wɝd/',
    'able': '/ˈebəl/',
    'abroad': '/əˈbrɔd/',
    'afraid': '/əˈfred/',
    'allow': '/əˈlaʊ/',
    'alone': '/əˈlon/',
    'apartment': '/əˈpɑrtmənt/',
    'attack': '/əˈtæk/',
    'beautiful': '/ˈbjutɪfəl/',
    'believe': '/bɪˈliv/',
    'better': '/ˈbɛtɚ/',
    'bike': '/baɪk/',
    'born': '/bɔrn/',
    'bottle': '/ˈbɑtl/',
    'camp': '/kæmp/',
    'card': '/kɑrd/',
    'care': '/kɛr/',
    'castle': '/ˈkæsəl/',
    'choose': '/tʃuz/',
    'collect': '/kəˈlɛkt/',
    'cool': '/kul/',
    'cost': '/kɔst/',
    'danger': '/ˈdendʒɚ/',
    'dark': '/dɑrk/',
    'date': '/deɪt/',
    'death': '/dɛθ/',
    'decide': '/dɪˈsaɪd/',
    'describe': '/dɪˈskraɪb/',
    'dinner': '/ˈdɪnɚ/',
    'direction': '/dɪˈrɛkʃən/',
    'discover': '/dɪˈskʌvɚ/',
    'distance': '/ˈdɪstəns/',
    'doctor': '/ˈdɑktɚ/',
    'doll': '/dɑl/',
    'draw': '/drɔ/',
    'dress': '/drɛs/',
    'drop': '/drɑp/',
    'duck': '/dʌk/',
    'explain': '/ɪkˈspleɪn/',
    'fact': '/fækt/',
    'farm': '/fɑrm/',
    'fat': '/fæt/',
    'fix': '/fɪks/',
    'follow': '/ˈfɑlo/',
    'force': '/fɔrs/',
    'foreign': '/ˈfɔrɪn/',
    'forest': '/ˈfɔrɪst/',
    'gift': '/ɡɪft/',
    'glass': '/ɡlæs/',
    'green': '/ɡrin/',
    'guess': '/ɡɛs/',
    'habit': '/ˈhæbɪt/',
    'happen': '/ˈhæpən/',
    'hate': '/heɪt/',
    'heat': '/hit/',
    'hide': '/haɪd/',
    'hill': '/hɪl/',
    'history': '/ˈhɪstrɪ/',
    'hold': '/hold/',
    'homework': '/ˈhomˌwɝk/',
    'hope': '/hop/',
    'hungry': '/ˈhʌŋɡrɪ/',
    'hunt': '/hʌnt/',
    'husband': '/ˈhʌzbənd/',
    'information': '/ˌɪnfɚˈmeʃən/',
    'insect': '/ˈɪnsɛkt/',
    'internet': '/ˈɪntɚˌnɛt/',
    'kill': '/kɪl/',
    'king': '/kɪŋ/',
    'kitchen': '/ˈkɪtʃɪn/',
    'knife': '/naɪf/',
    'land': '/lænd/',
    'lazy': '/ˈlezɪ/',
    'leader': '/ˈlidɚ/',
    'lend': '/lɛnd/',
    'lesson': '/ˈlɛsən/',
    'level': '/ˈlɛvəl/',
    'library': '/ˈlaɪˌbrɛrɪ/',
    'light': '/laɪt/',
    'list': '/lɪst/',
    'look': '/lʊk/',
    'loud': '/laʊd/',
    'lucky': '/ˈlʌkɪ/',
    'machine': '/məˈʃin/',
    'magic': '/ˈmædʒɪk/',
    'market': '/ˈmɑrkɪt/',
    'marry': '/ˈmærɪ/',
    'math': '/mæθ/',
    'meaning': '/ˈminɪŋ/',
    'medicine': '/ˈmɛdɪsɪn/',
    'meeting': '/ˈmitɪŋ/',
    'member': '/ˈmɛmbɚ/',
    'message': '/ˈmɛsɪdʒ/',
    'method': '/ˈmɛθəd/',
    'middle': '/ˈmɪdəl/',
    'modern': '/ˈmɑdɚn/',
    'moment': '/ˈmomənt/',
    'mountain': '/ˈmaʊntən/',
    'movie': '/ˈmuvɪ/',
    'national': '/ˈnæʃənəl/',
    'neck': '/nɛk/',
    'nest': '/nɛst/',
    'newspaper': '/ˈnjuzˌpeɪpɚ/',
    'origami': '/ˌɔrɪˈɡɑmɪ/',
    'overtime': '/ˈovɚˌtaɪm/',
    'owner': '/ˈonɚ/',
    'page': '/pedʒ/',
    'painting': '/ˈpentɪŋ/',
    'percent': '/pɚˈsɛnt/',
    'piano': '/pɪˈæno/',
    'pocket': '/ˈpɑkɪt/',
    'police': '/pəˈlis/',
    'postcard': '/ˈpostˌkɑrd/',
    'power': '/ˈpaʊɚ/',
    'prize': '/praɪz/',
    'protect': '/prəˈtɛkt/',
    'public': '/ˈpʌblɪk/',
    'pull': '/pʊl/',
    'queen': '/kwin/',
    'question': '/ˈkwɛstʃən/',
    'quickly': '/ˈkwɪklɪ/',
    'race': '/reɪs/',
    'reason': '/ˈrizən/',
    'receive': '/rɪˈsiv/',
    'refugee': '/ˌrɛfjʊˈdʒi/',
    'reporter': '/rɪˈpɔrtɚ/',
    'respect': '/rɪˈspɛkt/',
    'result': '/rɪˈzʌlt/',
    'return': '/rɪˈtɝn/',
    'river': '/ˈrɪvɚ/',
    'rock': '/rɑk/',
    'rule': '/rul/',
    'seat': '/sit/',
    'season': '/ˈsizən/',
    'sheep': '/ʃip/',
    'singer': '/ˈsɪŋɚ/',
    'sister': '/ˈsɪstɚ/',
    'size': '/saɪz/',
    'skill': '/skɪl/',
    'slow': '/slo/',
    'smart': '/smɑrt/',
    'snow': '/sno/',
    'society': '/səˈsaɪətɪ/',
    'song': '/sɔŋ/',
    'space': '/speɪs/',
    'speaker': '/ˈspikɚ/',
    'stage': '/stedʒ/',
    'state': '/steɪt/',
    'statue': '/ˈstætʃu/',
    'stay': '/steɪ/',
    'strange': '/strendʒ/',
    'street': '/strit/',
    'stupid': '/ˈstjupɪd/',
    'success': '/səkˈsɛs/',
    'table': '/ˈtebəl/',
    'taste': '/teɪst/',
    'team': '/tim/',
    'teaspoon': '/ˈtispun/',
    'technology': '/tɛkˈnɑlədʒɪ/',
    'teenager': '/ˈtinˌedʒɚ/',
    'telephone': '/ˈtɛləˌfon/',
    'terrible': '/ˈtɛrɪbəl/',
    'thousand': '/ˈθaʊzənd/',
    'throw': '/θro/',
    'thunder': '/ˈθʌndɚ/',
    'tonight': '/təˈnaɪt/',
    'touch': '/tʌtʃ/',
    'traffic': '/ˈtræfɪk/',
    'travel': '/ˈtrævəl/',
    'trick': '/trɪk/',
    'truck': '/trʌk/',
    'trust': '/trʌst/',
    'typhoon': '/taɪˈfun/',
    'umbrella': '/ʌmˈbrɛlə/',
    'uncle': '/ˈʌŋkəl/',
    'useful': '/ˈjusfəl/',
    'vacation': '/veˈkeʃən/',
    'vegetable': '/ˈvɛdʒɪtɪbəl/',
    'view': '/vju/',
    'wait': '/weɪt/',
    'waste': '/weɪst/',
    'website': '/ˈwɛbˌsaɪt/',
    'window': '/ˈwɪndo/',
    'winner': '/ˈwɪnɚ/',
    'wish': '/wɪʃ/',
    'wonderful': '/ˈwʌndɚfəl/',
    'worry': '/ˈwɝɪ/',
    'building': '/ˈbɪldɪŋ/',
    'point': '/pɔɪnt/',
    'second': '/ˈsɛkənd/',
    'eat': '/it/',
    'lie': '/laɪ/',
    'run': '/rʌn/',
    'go': '/ɡo/',
    'see': '/si/',
    'hear': '/hɪr/',
    'dance': '/dæns/',
    'sing': '/sɪŋ/',
    'jump': '/dʒʌmp/',
    'sleep': '/slip/',
    'borrow': '/ˈbɑro/',
    'catch': '/kætʃ/',
    'break': '/breɪk/',
    'bake': '/beɪk/',
    'burn': '/bɝn/',
    'cut': '/kʌt/',
    'repair': '/rɪˈpɛr/',
    'practice': '/ˈpræktɪs/',
    'celebrate': '/ˈsɛlɪˌbreɪt/',
    'complete': '/kəmˈplit/',
    'create': '/kriˈeɪt/',
    'design': '/dɪˈzaɪn/',
    'explore': '/ɪkˈsplɔr/',
    'introduce': '/ˌɪntrəˈdjus/',
    'interview': '/ˈɪntɚˌvju/',
    'recommend': '/ˌrɛkəˈmɛnd/',
    'suggest': '/səˈdʒɛst/',
    'notice': '/ˈnotɪs/',
    'expect': '/ɪkˈspɛkt/',
    'produce': '/prəˈdjus/',
    'melt': '/mɛlt/',
    'push': '/pʊʃ/',
    'exciting': '/ɪkˈsaɪtɪŋ/',
    'excited': '/ɪkˈsaɪtɪd/',
    'excite': '/ɪkˈsaɪt/',
    'boring': '/ˈbɔrɪŋ/',
    'bore': '/bɔr/',
    'interesting': '/ˈɪntrɪstɪŋ/',
    'surprised': '/sɚˈpraɪzd/',
    'worried': '/ˈwɝɪd/',
    'scared': '/skɛrd/',
    'scare': '/skɛr/',
    'proud': '/praʊd/',
    'shy': '/ʃaɪ/',
    'brave': '/breɪv/',
    'honest': '/ˈɑnɪst/',
    'wise': '/waɪz/',
    'crazy': '/ˈkrezɪ/',
    'helpful': '/ˈhɛlpfəl/',
    'unhappy': '/ˌʌnˈhæpɪ/',
    'careful': '/ˈkɛrfəl/',
    'dangerous': '/ˈdendʒərəs/',
    'famous': '/ˈfeɪməs/',
    'serious': '/ˈsɪrɪəs/',
    'curious': '/ˈkjʊrɪəs/',
    'nervous': '/ˈnɝvəs/',
    'delicious': '/dɪˈlɪʃəs/',
    'dirty': '/ˈdɝtɪ/',
    'dry': '/draɪ/',
    'flat': '/flæt/',
    'fresh': '/frɛʃ/',
    'full': '/fʊl/',
    'heavy': '/ˈhɛvɪ/',
    'low': '/lo/',
    'narrow': '/ˈnæro/',
    'near': '/nɪr/',
    'quick': '/kwɪk/',
    'sharp': '/ʃɑrp/',
    'short': '/ʃɔrt/',
    'thick': '/θɪk/',
    'thin': '/θɪn/',
    'wide': '/waɪd/',
    'wild': '/waɪld/',
    'young': '/jʌŋ/',
    'early': '/ˈɝlɪ/',
    'easily': '/ˈizɪlɪ/',
    'clearly': '/ˈklɪrlɪ/',
    'suddenly': '/ˈsʌdənlɪ/',
    'quietly': '/ˈkwaɪɪtlɪ/',
    'happily': '/ˈhæpɪlɪ/',
    'hard': '/hɑrd/',
    'fast': '/fæst/',
    'slowly': '/ˈslolɪ/',
    'perhaps': '/pɚˈhæps/',
    'probably': '/ˈprɑbəblɪ/',
    'usually': '/ˈjuʒʊəlɪ/',
    'generally': '/ˈdʒɛnərəlɪ/',
    'mainly': '/ˈmenlɪ/',
    'truly': '/ˈtruːlɪ/',
    'clearly': '/ˈklɪrlɪ/',
    'especially': '/ɪˈspɛʃəlɪ/',
    'finally': '/ˈfaɪnəlɪ/',
    'nearly': '/ˈnɪrlɪ/',
    'mostly': '/ˈmostlɪ/',
    'sadly': '/ˈsædlɪ/',
    'surprisingly': '/sɚˈpraɪzɪŋlɪ/',
    'completely': '/kəmˈplitlɪ/',
    'carefully': '/ˈkɛrfəlɪ/',
    'deeply': '/ˈdiplɪ/',
    'widely': '/ˈwaɪdlɪ/',
    'strongly': '/ˈstrɔŋlɪ/',
    'quickly': '/ˈkwɪklɪ/',
    'social': '/ˈsoʃəl/',
    'distance': '/ˈdɪstəns/',
    'pandemic': '/pænˈdɛmɪk/',
    'comic': '/ˈkɑmɪk/',
    'effect': '/ɪˈfɛkt/',
    'furniture': '/ˈfɝnɪtʃɚ/',
    'cabinet': '/ˈkæbɪnɪt/',
    'sacrifice': '/ˈsækrɪˌfaɪs/',
    'electricity': '/ɪˌlɛkˈtrɪsɪtɪ/',
    'empathy': '/ˈɛmpəθɪ/',
    'advocate': '/ˈædvəkɪt/',
    'extinct': '/ɪkˈstɪŋkt/',
    'uninhabitable': '/ˌʌnɪnˈhæbɪtəbəl/',
    'resentful': '/rɪˈzɛntfəl/',
    'commute': '/kəˈmjut/',
    'palindrome': '/ˈpælɪnˌdrom/',
    'anagram': '/ˈænəˌɡræm/',
    'spelling': '/ˈspɛlɪŋ/',
    'sentence': '/ˈsɛntəns/',
    'manuscript': '/ˈmænjəˌskrɪpt/',
    'opera': '/ˈɑprə/',
    'hormone': '/ˈhɔrmon/',
    'melatonin': '/ˌmɛləˈtonɪn/',
    'cortisol': '/ˈkɔrtɪˌsɔl/',
    'calorie': '/ˈkælərɪ/',
    'mosquito': '/məˈskito/',
    'raindrop': '/ˈrenˌdrɑp/',
    'feather': '/ˈfɛðɚ/',
    'fleece': '/flis/',
    'trolling': '/ˈtrolɪŋ/',
    'troll': '/trol/',
    'birdwatch': '/ˈbɝdˌwɑtʃ/',
    'campground': '/ˈkæmpˌɡraʊnd/',
    'lodging': '/ˈlɑdʒɪŋ/',
    'hike': '/haɪk/',
    'trail': '/treɪl/',
    'headache': '/ˈhɛdˌeɪk/',
    'snack': '/snæk/',
    'garbage': '/ˈɡɑrbɪdʒ/',
    'balcony': '/ˈbælkənɪ/',
    'drawer': '/drɔr/',
    'bookstore': '/ˈbʊkˌstɔr/',
    'supermarket': '/ˈsupɚˌmɑrkɪt/',
    'refrigerator': '/rɪˈfrɪdʒəˌretɚ/',
    'potato': '/pəˈteto/',
    'banana': '/bəˈnænə/',
    'grape': '/ɡreɪp/',
    'strawberry': '/ˈstrɔˌbɛrɪ/',
    'cheesecake': '/ˈtʃizˌkeɪk/',
    'chocolate': '/ˈtʃɑklɪt/',
    'cola': '/ˈkolə/',
    'basket': '/ˈbæskɪt/',
    'bowl': '/bol/',
    'envelope': '/ˈɛnvəˌlop/',
    'kite': '/kaɪt/',
    'butterfly': '/ˈbʌtɚˌflaɪ/',
    'plane': '/pleɪn/',
    'ghost': '/ɡost/',
    'fool': '/ful/',
    'stranger': '/ˈstrendʒɚ/',
    'neighbor': '/ˈnebɚ/',
    'population': '/ˌpɑpjəˈleʃən/',
    'generation': '/ˌdʒɛnəˈreʃən/',
    'century': '/ˈsɛntʃərɪ/',
    'decade': '/ˈdɛkeɪd/',
    'anniversary': '/ˌænɪˈvɝsərɪ/',
    'climate': '/ˈklaɪmɪt/',
    'environment': '/ɪnˈvaɪrənmənt/',
    'pollution': '/pəˈluʃən/',
    'energy': '/ˈɛnɚdʒɪ/',
    'resource': '/ˈrisɔrs/',
    'culture': '/ˈkʌltʃɚ/',
    'tradition': '/trəˈdɪʃən/',
    'festival': '/ˈfɛstɪvəl/',
    'ceremony': '/ˈsɛrɪˌmonɪ/',
    'address': '/ˈædrɛs/',
    'advertisement': '/ˌædvɚˈtaɪzmənt/',
    'competition': '/ˌkɑmpɪˈtɪʃən/',
    'condition': '/kənˈdɪʃən/',
    'connection': '/kəˈnɛkʃən/',
    'conversation': '/ˌkɑnvɚˈseʃən/',
    'education': '/ˌɛdʒʊˈkeʃən/',
    'emotion': '/ɪˈmoʃən/',
    'example': '/ɪɡˈzæmpəl/',
    'expression': '/ɪkˈsprɛʃən/',
    'imagination': '/ɪˌmædʒɪˈneʃən/',
    'impression': '/ɪmˈprɛʃən/',
    'instruction': '/ɪnˈstrʌkʃən/',
    'invention': '/ɪnˈvɛnʃən/',
    'invitation': '/ˌɪnvɪˈteʃən/',
    'location': '/loˈkeʃən/',
    'organization': '/ˌɔrɡənɪˈzeʃən/',
    'permission': '/pɚˈmɪʃən/',
    'presentation': '/ˌprɛzənˈteʃən/',
    'production': '/prəˈdʌkʃən/',
    'protection': '/prəˈtɛkʃən/',
    'publication': '/ˌpʌblɪˈkeʃən/',
    'recommendation': '/ˌrɛkəmɛnˈdeʃən/',
    'reservation': '/ˌrɛzɚˈveʃən/',
    'situation': '/ˌsɪtʃuˈeʃən/',
    'solution': '/səˈluʃən/',
    'suggestion': '/səˈdʒɛstʃən/',
    'temperature': '/ˈtɛmprɪtʃɚ/',
    'transportation': '/ˌtrænspoˈteʃən/',
    'understanding': '/ˌʌndɚˈstændɪŋ/',
}

ZH = {
    'people': '人們',
    'time': '時間',
    'school': '學校',
    'work': '工作',
    'food': '食物',
    'life': '生活',
    'day': '天；白天',
    'train': '火車',
    'book': '書',
    'city': '城市',
    'think': '思考；認為',
    'read': '閱讀',
    'year': '年',
    'money': '金錢',
    'shop': '商店；購物',
    'friend': '朋友',
    'leave': '離開',
    'home': '家',
    'business': '生意；商業',
    'help': '幫助',
    'country': '國家',
    'know': '知道',
    'place': '地方',
    'buy': '購買',
    'coffee': '咖啡',
    'house': '房子',
    'change': '改變',
    'child': '孩子',
    'morning': '早上',
    'student': '學生',
    'learn': '學習',
    'live': '居住；活著',
    'pay': '付錢',
    'way': '方式；道路',
    'sleep': '睡覺；睡眠',
    'story': '故事',
    'drive': '駕駛',
    'party': '派對',
    'drink': '飲料；喝',
    'worker': '工人',
    'game': '遊戲；比賽',
    'exercise': '運動；練習',
    'picture': '圖片',
    'report': '報告',
    'visit': '參觀；拜訪',
    'week': '星期；週',
    'cook': '烹飪；廚師',
    'find': '找到；發現',
    'give': '給',
    'letter': '信件；字母',
    'line': '線；路線',
    'news': '新聞',
    'night': '夜晚',
    'teacher': '老師',
    'water': '水',
    'answer': '回答；答案',
    'car': '汽車',
    'enjoy': '享受',
    'feel': '感覺',
    'hour': '小時',
    'move': '移動；搬家',
    'open': '開放；打開',
    'town': '小鎮',
    'sugar': '糖',
    'birthday': '生日',
    'body': '身體',
    'chance': '機會',
    'class': '班級；課',
    'come': '來',
    'close': '關閉；靠近',
    'get': '得到',
    'kind': '種類；善良的',
    'job': '工作；職業',
    'language': '語言',
    'museum': '博物館',
    'plan': '計劃',
    'plant': '植物；種植',
    'problem': '問題',
    'start': '開始',
    'idea': '想法；主意',
    'side': '側面；方面',
    'surprise': '驚喜；使驚訝',
    'tree': '樹',
    'ask': '詢問',
    'bed': '床',
    'bus': '公車',
    'dead': '死亡；死的',
    'family': '家庭',
    'keep': '保持；繼續',
    'make': '製作；使',
    'mind': '心思；介意',
    'park': '公園；停車',
    'sure': '確定的',
    'age': '年齡',
    'animal': '動物',
    'boy': '男孩',
    'call': '打電話；叫',
    'decision': '決定',
    'door': '門',
    'late': '遲；晚的',
    'love': '愛',
    'man': '男人',
    'name': '名字',
    'say': '說',
    'stop': '停止',
    'take': '拿；帶走',
    'war': '戰爭',
    'brain': '大腦',
    'color': '顏色',
    'experience': '經驗',
    'face': '臉；面對',
    'fall': '落下；秋天',
    'farmer': '農夫',
    'free': '免費；自由的',
    'ground': '地面',
    'happy': '快樂的',
    'heart': '心；心臟',
    'lose': '失去；輸',
    'office': '辦公室',
    'price': '價格',
    'run': '跑',
    'safe': '安全的',
    'sea': '海洋',
    'send': '發送；寄',
    'speak': '說；講',
    'stand': '站立',
    'summer': '夏天',
    'true': '真實的',
    'turn': '轉；轉動',
    'understand': '理解',
    'use': '使用',
    'woman': '女人',
    'write': '寫',
    'act': '行動；表演',
    'bring': '帶來',
    'build': '建造',
    'cover': '覆蓋；封面',
    'different': '不同的',
    'electricity': '電力；電',
    'hot': '熱的',
    'hurt': '傷害；受傷',
    'ice': '冰',
    'island': '島嶼',
    'number': '數字；號碼',
    'oil': '石油；油',
    'photo': '照片',
    'piece': '一片；一件',
    'rain': '雨；下雨',
    'road': '道路',
    'save': '拯救；節省',
    'shoe': '鞋子',
    'show': '展示；節目',
    'sick': '生病的',
    'small': '小的',
    'sound': '聲音；聽起來',
    'special': '特別的',
    'spend': '花費；度過',
    'sport': '運動',
    'star': '星星；明星',
    'study': '研究；學習',
    'together': '一起',
    'try': '嘗試',
    'win': '贏',
    'world': '世界',
    'wrong': '錯誤的',
    'afternoon': '下午',
    'agree': '同意',
    'bird': '鳥',
    'bread': '麵包',
    'cake': '蛋糕',
    'children': '孩子們',
    'clean': '清潔；乾淨的',
    'clear': '清晰的',
    'die': '死亡',
    'dog': '狗',
    'dream': '夢想；夢',
    'earth': '地球；土地',
    'easy': '容易的',
    'evening': '傍晚',
    'eye': '眼睛',
    'fight': '戰鬥；打架',
    'fire': '火；解雇',
    'flower': '花',
    'fly': '飛',
    'forget': '忘記',
    'future': '未來',
    'girl': '女孩',
    'grow': '成長；種植',
    'hair': '頭髮',
    'hand': '手',
    'hard': '困難的；努力地',
    'head': '頭；負責人',
    'hit': '打；碰撞',
    'hospital': '醫院',
    'hotel': '旅館',
    'important': '重要的',
    'interest': '興趣；利息',
    'invite': '邀請',
    'join': '加入',
    'lake': '湖',
    'laugh': '笑',
    'map': '地圖',
    'meal': '一餐',
    'meet': '遇見；開會',
    'minute': '分鐘',
    'miss': '錯過；想念',
    'month': '月份',
    'nature': '自然',
    'need': '需要',
    'paper': '紙；報紙',
    'pass': '通過；傳遞',
    'person': '人；個人',
    'play': '玩耍；演奏',
    'popular': '受歡迎的',
    'possible': '可能的',
    'prepare': '準備',
    'put': '放',
    'ready': '準備好的',
    'remember': '記得',
    'restaurant': '餐廳',
    'rise': '上升',
    'sell': '賣',
    'service': '服務',
    'set': '設置；一套',
    'share': '分享；分擔',
    'shout': '大喊',
    'sign': '標誌；簽名',
    'smile': '微笑',
    'store': '商店；儲存',
    'strong': '強壯的',
    'subject': '科目；主題',
    'swim': '游泳',
    'talk': '談話',
    'tell': '告訴',
    'ticket': '票',
    'tired': '疲倦的',
    'toy': '玩具',
    'type': '類型；打字',
    'village': '村莊',
    'voice': '聲音；嗓音',
    'walk': '走路',
    'warm': '溫暖的',
    'watch': '觀看；手錶',
    'weather': '天氣',
    'weekend': '週末',
    'word': '詞；字',
    'able': '能夠的',
    'abroad': '在海外',
    'afraid': '害怕的',
    'allow': '允許',
    'alone': '獨自',
    'apartment': '公寓',
    'attack': '攻擊',
    'beautiful': '美麗的',
    'believe': '相信',
    'better': '更好的',
    'bike': '自行車',
    'born': '出生的',
    'bottle': '瓶子',
    'camp': '露營',
    'card': '卡片',
    'care': '照顧；在乎',
    'castle': '城堡',
    'choose': '選擇',
    'collect': '收集',
    'cool': '涼爽的；酷的',
    'cost': '花費；成本',
    'danger': '危險',
    'dark': '黑暗的',
    'date': '日期',
    'death': '死亡',
    'decide': '決定',
    'describe': '描述',
    'dinner': '晚餐',
    'direction': '方向',
    'discover': '發現',
    'distance': '距離',
    'doctor': '醫生',
    'doll': '洋娃娃',
    'draw': '畫；拉',
    'dress': '洋裝；穿著',
    'drop': '落下；滴',
    'duck': '鴨子',
    'explain': '解釋',
    'fact': '事實',
    'farm': '農場',
    'fat': '脂肪；肥胖的',
    'fix': '修理；解決',
    'follow': '跟隨',
    'force': '力量；強迫',
    'foreign': '外國的',
    'forest': '森林',
    'gift': '禮物',
    'glass': '玻璃；杯子',
    'green': '綠色的',
    'guess': '猜測',
    'habit': '習慣',
    'happen': '發生',
    'hate': '憎恨',
    'heat': '熱；加熱',
    'hide': '躲藏；隱藏',
    'hill': '山丘',
    'history': '歷史',
    'hold': '持有；舉行',
    'homework': '作業',
    'hope': '希望',
    'hungry': '飢餓的',
    'hunt': '打獵；搜尋',
    'husband': '丈夫',
    'information': '資訊',
    'insect': '昆蟲',
    'internet': '網際網路',
    'kill': '殺死',
    'king': '國王',
    'kitchen': '廚房',
    'knife': '刀',
    'land': '陸地；降落',
    'lazy': '懶惰的',
    'leader': '領導者',
    'lend': '借出',
    'lesson': '課；教訓',
    'level': '水平；程度',
    'library': '圖書館',
    'light': '光；燈；輕的',
    'list': '清單',
    'look': '看',
    'loud': '大聲的',
    'lucky': '幸運的',
    'machine': '機器',
    'magic': '魔法',
    'market': '市場',
    'marry': '結婚',
    'math': '數學',
    'meaning': '意思',
    'medicine': '藥物；醫學',
    'meeting': '會議',
    'member': '成員',
    'message': '訊息',
    'method': '方法',
    'middle': '中間的',
    'modern': '現代的',
    'moment': '時刻',
    'mountain': '山',
    'movie': '電影',
    'national': '國家的',
    'neck': '脖子',
    'nest': '鳥巢',
    'newspaper': '報紙',
    'origami': '摺紙',
    'overtime': '加班',
    'owner': '擁有者',
    'page': '頁',
    'painting': '畫作；繪畫',
    'percent': '百分之',
    'piano': '鋼琴',
    'pocket': '口袋',
    'police': '警察',
    'postcard': '明信片',
    'power': '力量；電力',
    'prize': '獎品',
    'protect': '保護',
    'public': '公共的',
    'pull': '拉',
    'queen': '女王',
    'question': '問題',
    'quickly': '迅速地',
    'race': '比賽；種族',
    'reason': '原因',
    'receive': '收到',
    'refugee': '難民',
    'reporter': '記者',
    'respect': '尊敬；尊重',
    'result': '結果',
    'return': '返回',
    'river': '河流',
    'rock': '岩石',
    'rule': '規則',
    'seat': '座位',
    'season': '季節',
    'sheep': '羊',
    'singer': '歌手',
    'sister': '姊妹',
    'size': '尺寸',
    'skill': '技能',
    'slow': '慢的',
    'smart': '聰明的',
    'snow': '雪',
    'society': '社會',
    'song': '歌曲',
    'space': '空間；太空',
    'speaker': '演說者；喇叭',
    'stage': '舞台；階段',
    'state': '狀態；陳述',
    'statue': '雕像',
    'stay': '留下',
    'strange': '奇怪的',
    'street': '街道',
    'stupid': '愚蠢的',
    'success': '成功',
    'table': '桌子',
    'taste': '味道；品嚐',
    'team': '團隊',
    'teaspoon': '茶匙',
    'technology': '科技',
    'teenager': '青少年',
    'telephone': '電話',
    'terrible': '可怕的',
    'thousand': '千',
    'throw': '投擲；扔',
    'thunder': '雷聲',
    'tonight': '今晚',
    'touch': '觸摸',
    'traffic': '交通',
    'travel': '旅行',
    'trick': '把戲；欺騙',
    'truck': '卡車',
    'trust': '信任',
    'typhoon': '颱風',
    'umbrella': '雨傘',
    'uncle': '叔叔；舅舅',
    'useful': '有用的',
    'vacation': '假期',
    'vegetable': '蔬菜',
    'view': '景色；觀點',
    'wait': '等待',
    'waste': '浪費',
    'website': '網站',
    'window': '窗戶',
    'winner': '勝利者',
    'wish': '願望；希望',
    'wonderful': '很棒的',
    'worry': '擔心',
    'building': '建築物',
    'point': '點；重點',
    'eat': '吃',
    'lie': '說謊；躺',
    'go': '去',
    'see': '看見',
    'hear': '聽到',
    'dance': '跳舞',
    'sing': '唱歌',
    'jump': '跳',
    'borrow': '借入',
    'catch': '抓住',
    'break': '打破',
    'bake': '烤',
    'burn': '燃燒',
    'cut': '切',
    'repair': '修理',
    'practice': '練習',
    'celebrate': '慶祝',
    'complete': '完成',
    'create': '創造',
    'design': '設計',
    'explore': '探索',
    'introduce': '介紹',
    'interview': '面試；採訪',
    'recommend': '推薦',
    'suggest': '建議',
    'notice': '注意',
    'expect': '期待',
    'produce': '生產',
    'melt': '融化',
    'push': '推',
    'excite': '使興奮',
    'bore': '使厭倦',
    'scare': '使害怕',
    'proud': '驕傲的',
    'shy': '害羞的',
    'brave': '勇敢的',
    'honest': '誠實的',
    'wise': '聰明的；明智的',
    'crazy': '瘋狂的',
    'helpful': '有幫助的',
    'unhappy': '不快樂的',
    'careful': '小心的',
    'dangerous': '危險的',
    'famous': '著名的',
    'serious': '嚴肅的；嚴重的',
    'curious': '好奇的',
    'nervous': '緊張的',
    'delicious': '美味的',
    'dirty': '骯髒的',
    'dry': '乾燥的',
    'fresh': '新鮮的',
    'full': '滿的',
    'heavy': '重的',
    'low': '低的',
    'narrow': '狹窄的',
    'near': '靠近的',
    'quick': '迅速的',
    'sharp': '鋒利的',
    'short': '短的；矮的',
    'thick': '厚的',
    'thin': '薄的；瘦的',
    'wide': '寬的',
    'wild': '野生的；狂野的',
    'young': '年輕的',
    'early': '早的；早地',
    'fast': '快速的；快速地',
    'perhaps': '也許',
    'probably': '可能地',
    'usually': '通常地',
    'finally': '最終地',
    'nearly': '幾乎',
    'sadly': '悲傷地',
    'quickly': '迅速地',
    'social': '社交的',
    'pandemic': '大流行病',
    'comic': '漫畫',
    'effect': '效應；效果',
    'furniture': '家具',
    'cabinet': '櫃子',
    'sacrifice': '犧牲',
    'electricity': '電力',
    'empathy': '同理心',
    'advocate': '倡導者',
    'extinct': '絕種的',
    'uninhabitable': '不適合居住的',
    'resentful': '憤恨的',
    'commute': '通勤',
    'palindrome': '迴文',
    'anagram': '字謎重組',
    'manuscript': '手稿',
    'opera': '歌劇',
    'hormone': '荷爾蒙',
    'melatonin': '褪黑激素',
    'cortisol': '皮質醇',
    'calorie': '卡路里',
    'mosquito': '蚊子',
    'raindrop': '雨滴',
    'feather': '羽毛',
    'fleece': '羊毛',
    'troll': '網路酸民；釣魚',
    'campground': '露營地',
    'lodging': '住宿',
    'hike': '健行',
    'trail': '步道',
    'headache': '頭痛',
    'snack': '點心',
    'garbage': '垃圾',
    'balcony': '陽台',
    'drawer': '抽屜',
    'bookstore': '書店',
    'supermarket': '超市',
    'refrigerator': '冰箱',
    'strawberry': '草莓',
    'cheesecake': '起司蛋糕',
    'chocolate': '巧克力',
    'basket': '籃子',
    'bowl': '碗',
    'envelope': '信封',
    'kite': '風箏',
    'butterfly': '蝴蝶',
    'plane': '飛機',
    'ghost': '鬼',
    'fool': '傻瓜',
    'stranger': '陌生人',
    'neighbor': '鄰居',
    'population': '人口',
    'generation': '世代',
    'century': '世紀',
    'festival': '節日；慶典',
    'address': '地址',
    'competition': '競賽',
    'condition': '條件；狀況',
    'education': '教育',
    'emotion': '情緒',
    'example': '例子',
    'expression': '表達；表情',
    'invention': '發明',
    'invitation': '邀請函',
    'organization': '組織',
    'permission': '允許',
    'presentation': '報告；呈現',
    'protection': '保護',
    'situation': '情況',
    'solution': '解決方案',
    'suggestion': '建議',
    'temperature': '溫度',
    'transportation': '交通運輸',
}

print("KK and ZH dicts defined. Script complete.")
print(f"KK entries: {len(KK)}")
print(f"ZH entries: {len(ZH)}")
