# fill_all_vocab.py
import openpyxl

# 完整的音標和詞性資料（基於 wordlist.md + 標準字典）
vocab_complete = {
    # A (共約 120 字)
    'able': ('[ˈeɪbəl]', '(形) 能...的'),
    'about': ('[əˈbaʊt]', '(介) 關於、(副) 大約'),
    'above': ('[əˈbʌv]', '(介) 在...上方、(副) 在上面'),
    'abroad': ('[əˈbrɔd]', '(副) 到國外'),
    'absent': ('[ˈæbsənt]', '(形) 缺席的'),
    'accept': ('[əkˈsɛpt]', '(動) 接受'),
    'accident': ('[ˈæksədənt]', '(名) 意外事故'),
    'across': ('[əˈkrɔs]', '(介) 穿過、(副) 對面'),
    'act': ('[ækt]', '(動) 行動；表演、(名) 行為'),
    'action': ('[ˈækʃən]', '(名) 行動'),
    'active': ('[ˈæktɪv]', '(形) 活躍的'),
    'activity': ('[ækˈtɪvəti]', '(名) 活動'),
    'actor': ('[ˈæktɚ]', '(名) 演員'),
    'actress': ('[ˈæktrəs]', '(名) 女演員'),
    'actually': ('[ˈæktʃuəli]', '(副) 實際上'),
    'add': ('[æd]', '(動) 添加'),
    'address': ('[əˈdrɛs]', '(名) 地址、(動) 處理'),
    'admire': ('[ədˈmaɪr]', '(動) 欽佩'),
    'adult': ('[əˈdʌlt]', '(名) 成人、(形) 成年的'),
    'advertisement': ('[ˌædvɚˈtaɪzmənt]', '(名) 廣告'),
    'advice': ('[ədˈvaɪs]', '(名) 建議'),
    'advise': ('[ədˈvaɪz]', '(動) 建議'),
    'affect': ('[əˈfɛkt]', '(動) 影響'),
    'afraid': ('[əˈfred]', '(形) 害怕的'),
    'after': ('[ˈæftɚ]', '(介) 在...之後、(連) 在...之後'),
    'afternoon': ('[ˌæftɚˈnun]', '(名) 下午'),
    'again': ('[əˈɡɛn]', '(副) 再一次'),
    'against': ('[əˈɡɛnst]', '(介) 反對'),
    'age': ('[edʒ]', '(名) 年齡、(動) 變老'),
    'ago': ('[əˈɡoʊ]', '(副) 以前'),
    'agree': ('[əˈɡri]', '(動) 同意'),
    'ahead': ('[əˈhɛd]', '(副) 在前面'),
    'aim': ('[em]', '(動) 瞄準、(名) 目標'),
    'air': ('[ɛr]', '(名) 空氣'),
    'airplane': ('[ˈɛrˌplen]', '(名) 飛機'),
    'airport': ('[ˈɛrˌpɔrt]', '(名) 機場'),
    'alarm': ('[əˈlɑrm]', '(名) 警報器、(動) 使驚慌'),
    'album': ('[ˈælbəm]', '(名) 專輯；相簿'),
    'alike': ('[əˈlaɪk]', '(形) 相似的、(副) 同樣地'),
    'alive': ('[əˈlaɪv]', '(形) 活著的'),
    'all': ('[ɔl]', '(代) 全部、(形) 所有的'),
    'allow': ('[əˈlaʊ]', '(動) 允許'),
    'almost': ('[ˈɔlˌmoʊst]', '(副) 幾乎'),
    'alone': ('[əˈloʊn]', '(形) 單獨的、(副) 獨自地'),
    'along': ('[əˈlɔŋ]', '(介) 沿著、(副) 一起'),
    'aloud': ('[əˈlaʊd]', '(副) 大聲地'),
    'already': ('[ɔlˈrɛdi]', '(副) 已經'),
    'also': ('[ˈɔlsoʊ]', '(副) 也'),
    'altogether': ('[ˌɔltəˈɡɛðɚ]', '(副) 總共；完全'),
    'always': ('[ˈɔlweɪz]', '(副) 總是'),
    'ambulance': ('[ˈæmbjələns]', '(名) 救護車'),
    'among': ('[əˈmʌŋ]', '(介) 在...之中'),
    'ancient': ('[ˈenʃənt]', '(形) 古代的'),
    'angel': ('[ˈendʒəl]', '(名) 天使'),
    'anger': ('[ˈæŋɡɚ]', '(名) 憤怒、(動) 使生氣'),
    'angry': ('[ˈæŋɡri]', '(形) 生氣的'),
    'ankle': ('[ˈæŋkəl]', '(名) 腳踝'),
    'animal': ('[ˈænɪməl]', '(名) 動物'),
    'another': ('[əˈnʌðɚ]', '(代) 另一個、(形) 別的'),
    'answer': ('[ˈænsɚ]', '(名/動) 答案；回答'),
    'ant': ('[ænt]', '(名) 螞蟻'),
    'any': ('[ˈɛni]', '(代) 任何、(形) 任何的'),
    'anyone': ('[ˈɛniˌwʌn]', '(代) 任何人'),
    'anything': ('[ˈɛniˌθɪŋ]', '(代) 任何事物'),
    'anywhere': ('[ˈɛniˌwɛr]', '(副) 任何地方'),
    'apartment': ('[əˈpɑrtmənt]', '(名) 公寓'),
    'apologize': ('[əˈpɑləˌdʒaɪz]', '(動) 道歉'),
    'appear': ('[əˈpɪr]', '(動) 出現'),
    'apple': ('[ˈæpəl]', '(名) 蘋果'),
    'appreciate': ('[əˈpriʃiˌet]', '(動) 欣賞；感激'),
    'area': ('[ˈɛriə]', '(名) 地區'),
    'argue': ('[ˈɑrɡju]', '(動) 爭論'),
    'arm': ('[ɑrm]', '(名) 手臂'),
    'armchair': ('[ˈɑrmˌtʃɛr]', '(名) 扶手椅'),
    'army': ('[ˈɑrmi]', '(名) 軍隊'),
    'around': ('[əˈraʊnd]', '(介) 圍繞、(副) 大約'),
    'arrange': ('[əˈrendʒ]', '(動) 安排'),
    'arrive': ('[əˈraɪv]', '(動) 到達'),
    'art': ('[ɑrt]', '(名) 藝術'),
    'artist': ('[ˈɑrtɪst]', '(名) 藝術家'),
    'as': ('[æz]', '(連) 如同；當...時、(介) 作為'),
    'ask': ('[æsk]', '(動) 問；要求'),
    'asleep': ('[əˈslip]', '(形) 睡著的'),
    'assistant': ('[əˈsɪstənt]', '(名) 助手'),
    'assume': ('[əˈsum]', '(動) 假定'),
    'attack': ('[əˈtæk]', '(動/名) 攻擊'),
    'attention': ('[əˈtɛnʃən]', '(名) 注意'),
    'aunt': ('[ænt]', '(名) 阿姨；姑姑'),
    'autumn': ('[ˈɔtəm]', '(名) 秋天'),
    'available': ('[əˈveləbəl]', '(形) 可得到的'),
    'avoid': ('[əˈvɔɪd]', '(動) 避免'),
    'away': ('[əˈweɪ]', '(副) 離開'),
    
    # B (前 60 字)
    'baby': ('[ˈbeɪbi]', '(名) 嬰兒'),
    'babysitter': ('[ˈbeɪbiˌsɪtɚ]', '(名) 保姆'),
    'back': ('[bæk]', '(名) 背部、(副) 回來、(動) 支持'),
    'backward': ('[ˈbækwɚd]', '(形/副) 向後的'),
    'bad': ('[bæd]', '(形) 壞的'),
    'badminton': ('[ˈbædmɪntən]', '(名) 羽毛球'),
    'bag': ('[bæɡ]', '(名) 袋子'),
    'bake': ('[bek]', '(動) 烘焙'),
    'bakery': ('[ˈbekəri]', '(名) 麵包店'),
    'balcony': ('[ˈbælkəni]', '(名) 陽台'),
    'ball': ('[bɔl]', '(名) 球'),
    'balloon': ('[bəˈlun]', '(名) 氣球'),
    'banana': ('[bəˈnænə]', '(名) 香蕉'),
    'band': ('[bænd]', '(名) 樂隊'),
    'bank': ('[bæŋk]', '(名) 銀行'),
    'barbecue': ('[ˈbɑrbɪˌkju]', '(名/動) 烤肉'),
    'barber': ('[ˈbɑrbɚ]', '(名) 理髮師'),
    'bark': ('[bɑrk]', '(動) 狗叫、(名) 樹皮'),
    'base': ('[bes]', '(名) 基礎、(動) 以...為基礎'),
    'baseball': ('[ˈbesˌbɔl]', '(名) 棒球'),
    'basement': ('[ˈbesmənt]', '(名) 地下室'),
    'basic': ('[ˈbesɪk]', '(形) 基本的'),
    'basket': ('[ˈbæskɪt]', '(名) 籃子'),
    'basketball': ('[ˈbæskətˌbɔl]', '(名) 籃球'),
    'bat': ('[bæt]', '(名) 蝙蝠；球棒'),
    'bath': ('[bæθ]', '(名) 洗澡'),
    'bathe': ('[beð]', '(動) 沐浴'),
    'bathroom': ('[ˈbæθˌrum]', '(名) 浴室'),
    'beach': ('[bitʃ]', '(名) 海灘'),
    'bean': ('[bin]', '(名) 豆子'),
    'bear': ('[bɛr]', '(名) 熊、(動) 忍受'),
    'beard': ('[bɪrd]', '(名) 鬍子'),
    'beat': ('[bit]', '(動) 打敗；敲打'),
    'beautiful': ('[ˈbjutəfəl]', '(形) 美麗的'),
    'beauty': ('[ˈbjuti]', '(名) 美麗'),
    'because': ('[bɪˈkɔz]', '(連) 因為'),
    'become': ('[bɪˈkʌm]', '(動) 變成'),
    'bed': ('[bɛd]', '(名) 床'),
    'bedroom': ('[ˈbɛdˌrum]', '(名) 臥室'),
    'bee': ('[bi]', '(名) 蜜蜂'),
    'beef': ('[bif]', '(名) 牛肉'),
    'beer': ('[bɪr]', '(名) 啤酒'),
    'before': ('[bɪˈfɔr]', '(介/連) 在...之前'),
    'begin': ('[bɪˈɡɪn]', '(動) 開始'),
    'beginner': ('[bɪˈɡɪnɚ]', '(名) 初學者'),
    'beginning': ('[bɪˈɡɪnɪŋ]', '(名) 開始'),
    'behave': ('[bɪˈhev]', '(動) 表現'),
    'behind': ('[bɪˈhaɪnd]', '(介) 在...後面'),
    'believe': ('[bɪˈliv]', '(動) 相信'),
    'bell': ('[bɛl]', '(名) 鈴鐺'),
    'belong': ('[bɪˈlɔŋ]', '(動) 屬於'),
    'below': ('[bɪˈloʊ]', '(介) 在...下面'),
    'belt': ('[bɛlt]', '(名) 皮帶'),
    'bench': ('[bɛntʃ]', '(名) 長椅'),
    'besides': ('[bɪˈsaɪdz]', '(介/副) 除此之外'),
    'between': ('[bɪˈtwin]', '(介) 在...之間'),
    'beyond': ('[bɪˈjɑnd]', '(介) 超出'),
    'bicycle': ('[ˈbaɪsɪkəl]', '(名) 腳踏車'),
    'big': ('[bɪɡ]', '(形) 大的'),
    'bill': ('[bɪl]', '(名) 帳單'),
    
    # 後續單字會繼續補充...
}

wb = openpyxl.load_workbook('2000voc.xlsx')
ws = wb.active

count = 0
for row in range(2, ws.max_row + 1):
    word = ws[f'A{row}'].value
    if word and word.lower() in vocab_complete:
        phonetic, pos = vocab_complete[word.lower()]
        if not ws[f'B{row}'].value:
            ws[f'B{row}'] = phonetic
            count += 1
        if not ws[f'C{row}'].value:
            ws[f'C{row}'] = pos
            count += 1

wb.save('2000voc.xlsx')
print(f"已更新 {count} 個欄位")