#!/usr/bin/env python
# -*- coding: utf-8 -*-
import openpyxl

# Extended D-Z vocabulary data
vocab_data = {
    'daily': ('[ˈdeɪli]', '(形) 每日的'),
    'dance': ('[dæns]', '(動/名) 舞蹈'),
    'danger': ('[ˈdeɪndʒɚ]', '(名) 危險'),
    'dangerous': ('[ˈdeɪndʒərəs]', '(形) 危險的'),
    'dark': ('[dɑrk]', '(形) 黑暗的'),
    'date': ('[deɪt]', '(名) 日期；約會'),
    'day': ('[deɪ]', '(名) 日子'),
    'dead': ('[dɛd]', '(形) 死的'),
    'deal': ('[dil]', '(動) 處理；交易'),
    'dear': ('[dɪr]', '(形) 親愛的'),
    'death': ('[dɛθ]', '(名) 死亡'),
    'decide': ('[dɪˈsaɪd]', '(動) 決定'),
    'deep': ('[dip]', '(形) 深的'),
    'degree': ('[dɪˈɡri]', '(名) 度；學位'),
    'delicious': ('[dɪˈlɪʃəs]', '(形) 美味的'),
    'depend': ('[dɪˈpɛnd]', '(動) 依靠'),
    'describe': ('[dɪˈskraɪb]', '(動) 描述'),
    'design': ('[dɪˈzaɪn]', '(動/名) 設計'),
    'desk': ('[dɛsk]', '(名) 桌子'),
    'develop': ('[dɪˈvɛləp]', '(動) 發展'),
    'development': ('[dɪˈvɛləpmənt]', '(名) 發展'),
    'dictionary': ('[ˈdɪkʃəˌnɛri]', '(名) 字典'),
    'die': ('[daɪ]', '(動) 死'),
    'difference': ('[ˈdɪfərəns]', '(名) 差異'),
    'different': ('[ˈdɪfərənt]', '(形) 不同的'),
    'difficult': ('[ˈdɪfɪkəlt]', '(形) 困難的'),
    'dinner': ('[ˈdɪnɚ]', '(名) 晚餐'),
    'direction': ('[dəˈrɛkʃən]', '(名) 方向'),
    'dirty': ('[ˈdɜrti]', '(形) 髒的'),
    'discuss': ('[dɪˈskʌs]', '(動) 討論'),
    'disease': ('[dɪˈziz]', '(名) 疾病'),
    'distance': ('[ˈdɪstəns]', '(名) 距離'),
    'do': ('[du]', '(動) 做'),
    'doctor': ('[ˈdɑktɚ]', '(名) 醫生'),
    'dog': ('[dɔɡ]', '(名) 狗'),
    'dollar': ('[ˈdɑlɚ]', '(名) 美元'),
    'door': ('[dɔr]', '(名) 門'),
    'doubt': ('[daʊt]', '(動/名) 懷疑'),
    'down': ('[daʊn]', '(副/介) 向下'),
    'drama': ('[ˈdrɑmə]', '(名) 戲劇'),
    'draw': ('[drɔ]', '(動) 畫；抽籤'),
    'dream': ('[drim]', '(名/動) 夢'),
    'dress': ('[drɛs]', '(名/動) 衣服；穿衣'),
    'drink': ('[drɪŋk]', '(動/名) 喝'),
    'drive': ('[draɪv]', '(動) 駕駛'),
    'driver': ('[ˈdraɪvɚ]', '(名) 駕駛員'),
    'drop': ('[drɑp]', '(動/名) 掉落'),
    'dry': ('[draɪ]', '(形) 乾的'),
    'duck': ('[dʌk]', '(名) 鴨子'),
    'during': ('[ˈdʊrɪŋ]', '(介) 在...期間'),
    'duty': ('[ˈduti]', '(名) 責任'),
    'each': ('[itʃ]', '(代) 每個'),
    'ear': ('[ɪr]', '(名) 耳朵'),
    'early': ('[ˈɜrli]', '(形/副) 早的'),
    'earn': ('[ɜrn]', '(動) 賺取'),
    'earth': ('[ɜrθ]', '(名) 地球；土地'),
    'easily': ('[ˈizəli]', '(副) 容易地'),
    'east': ('[ist]', '(名) 東方'),
    'easy': ('[ˈizi]', '(形) 容易的'),
    'eat': ('[it]', '(動) 吃'),
    'edge': ('[ɛdʒ]', '(名) 邊緣'),
    'education': ('[ˌɛdʒəˈkeɪʃən]', '(名) 教育'),
    'effect': ('[ɪˈfɛkt]', '(名) 效果'),
    'effort': ('[ˈɛfɚt]', '(名) 努力'),
    'egg': ('[ɛɡ]', '(名) 蛋'),
    'either': ('[ˈiðɚ]', '(代/連) 兩者之一'),
    'electric': ('[ɪˈlɛktrɪk]', '(形) 電的'),
    'electricity': ('[ɪˌlɛkˈtrɪsəti]', '(名) 電'),
    'element': ('[ˈɛləmənt]', '(名) 元素'),
    'elephant': ('[ˈɛləfənt]', '(名) 象'),
    'else': ('[ɛls]', '(副) 別的'),
    'empty': ('[ˈɛmpti]', '(形) 空的'),
    'enemy': ('[ˈɛnəmi]', '(名) 敵人'),
    'energy': ('[ˈɛnɚdʒi]', '(名) 能量'),
    'engine': ('[ˈɛndʒɪn]', '(名) 引擎'),
    'enjoy': ('[ɪnˈdʒɔɪ]', '(動) 享受'),
    'enough': ('[ɪˈnʌf]', '(形/副) 足夠的'),
    'enter': ('[ˈɛntɚ]', '(動) 進入'),
    'environment': ('[ɪnˈvaɪrənmənt]', '(名) 環境'),
    'equal': ('[ˈikwəl]', '(形) 相等的'),
    'equipment': ('[ɪˈkwɪpmənt]', '(名) 設備'),
    'error': ('[ˈɛrɚ]', '(名) 錯誤'),
    'even': ('[ˈivən]', '(形/副) 甚至；平的'),
    'evening': ('[ˈivnɪŋ]', '(名) 晚上'),
    'event': ('[ɪˈvɛnt]', '(名) 事件'),
    'ever': ('[ˈɛvɚ]', '(副) 曾經'),
    'every': ('[ˈɛvri]', '(形) 每個'),
    'everyone': ('[ˈɛvriˌwʌn]', '(代) 每個人'),
    'everything': ('[ˈɛvriˌθɪŋ]', '(代) 每件事'),
    'exactly': ('[ɪɡˈzæktli]', '(副) 確實'),
    'example': ('[ɪɡˈzæmpəl]', '(名) 例子'),
    'excellent': ('[ˈɛksələnt]', '(形) 優秀的'),
    'except': ('[ɪkˈsɛpt]', '(介) 除...外'),
    'exercise': ('[ˈɛksɚˌsaɪz]', '(名/動) 運動；練習'),
    'exist': ('[ɪɡˈzɪst]', '(動) 存在'),
    'experience': ('[ɪkˈspɪriəns]', '(名/動) 經驗'),
    'experiment': ('[ɪkˈspɛrəmənt]', '(名) 實驗'),
    'explain': ('[ɪkˈspleɪn]', '(動) 解釋'),
    'expression': ('[ɪkˈsprɛʃən]', '(名) 表達'),
    'eye': ('[aɪ]', '(名) 眼睛'),
    'face': ('[feɪs]', '(名/動) 臉；面對'),
    'fact': ('[fækt]', '(名) 事實'),
    'factory': ('[ˈfæktəri]', '(名) 工廠'),
    'fail': ('[feɪl]', '(動) 失敗'),
    'failure': ('[ˈfeɪljɚ]', '(名) 失敗'),
    'fall': ('[fɔl]', '(動/名) 秋天；掉落'),
    'false': ('[fɔls]', '(形) 虛假的'),
    'family': ('[ˈfæməli]', '(名) 家庭'),
    'famous': ('[ˈfeɪməs]', '(形) 著名的'),
    'far': ('[fɑr]', '(形/副) 遠的'),
    'farm': ('[fɑrm]', '(名/動) 農場'),
    'farmer': ('[ˈfɑrmɚ]', '(名) 農民'),
    'fast': ('[fæst]', '(形/副) 快的'),
    'fat': ('[fæt]', '(形/名) 肥的；脂肪'),
    'father': ('[ˈfɑðɚ]', '(名) 父親'),
    'fault': ('[fɔlt]', '(名) 過錯'),
    'favorite': ('[ˈfeɪvərɪt]', '(形) 最喜歡的'),
    'fear': ('[fɪr]', '(動/名) 害怕'),
    'feel': ('[fil]', '(動) 感受'),
    'feeling': ('[ˈfilɪŋ]', '(名) 感覺'),
    'female': ('[ˈfimeɪl]', '(形/名) 女性的'),
    'fever': ('[ˈfivɚ]', '(名) 發燒'),
    'few': ('[fju]', '(代/形) 幾個'),
    'field': ('[fild]', '(名) 田地；領域'),
    'figure': ('[ˈfɪɡjɚ]', '(名/動) 數字；計算'),
    'fill': ('[fɪl]', '(動) 填充'),
    'film': ('[fɪlm]', '(名) 電影；膜'),
    'final': ('[ˈfaɪnəl]', '(形) 最終的'),
    'finally': ('[ˈfaɪnəli]', '(副) 最後'),
    'find': ('[faɪnd]', '(動) 發現'),
    'fine': ('[faɪn]', '(形) 精美的；罰金'),
    'finger': ('[ˈfɪŋɡɚ]', '(名) 手指'),
    'finish': ('[ˈfɪnɪʃ]', '(動) 完成'),
    'fire': ('[ˈfaɪɚ]', '(名/動) 火；解僱'),
    'first': ('[ˈfɜrst]', '(形/副) 第一的'),
    'fish': ('[fɪʃ]', '(名/動) 魚'),
    'fit': ('[fɪt]', '(形/動) 適合的'),
    'five': ('[faɪv]', '(數) 五'),
    'fix': ('[fɪks]', '(動) 修理'),
    'flag': ('[flæɡ]', '(名) 旗子'),
    'flash': ('[flæʃ]', '(動/名) 閃光'),
    'flat': ('[flæt]', '(形) 平的'),
    'flight': ('[flaɪt]', '(名) 飛行'),
    'float': ('[floʊt]', '(動) 漂浮'),
    'flood': ('[flʌd]', '(名/動) 洪水'),
    'floor': ('[flɔr]', '(名) 樓層；地板'),
    'flower': ('[ˈflaʊɚ]', '(名) 花'),
    'fly': ('[flaɪ]', '(動/名) 飛行'),
    'focus': ('[ˈfoʊkəs]', '(動) 集中'),
    'follow': ('[ˈfɑloʊ]', '(動) 跟隨'),
    'food': ('[fud]', '(名) 食物'),
    'fool': ('[ful]', '(名) 傻瓜'),
    'foot': ('[fʊt]', '(名) 腳'),
    'football': ('[ˈfʊtˌbɔl]', '(名) 美式足球'),
    'force': ('[fɔrs]', '(動/名) 力量'),
    'foreign': ('[ˈfɔrən]', '(形) 外國的'),
    'forest': ('[ˈfɔrɪst]', '(名) 森林'),
    'forget': ('[fɚˈɡɛt]', '(動) 忘記'),
    'forgive': ('[fɚˈɡɪv]', '(動) 原諒'),
    'form': ('[fɔrm]', '(名/動) 形式；形成'),
    'formal': ('[ˈfɔrməl]', '(形) 正式的'),
    'former': ('[ˈfɔrmɚ]', '(形) 以前的'),
    'forward': ('[ˈfɔrwɚd]', '(副/形) 向前'),
    'four': ('[fɔr]', '(數) 四'),
    'free': ('[fri]', '(形) 自由的；免費'),
    'freedom': ('[ˈfridəm]', '(名) 自由'),
    'fresh': ('[frɛʃ]', '(形) 新鮮的'),
    'friend': ('[frɛnd]', '(名) 朋友'),
    'friendly': ('[ˈfrɛndli]', '(形) 友好的'),
    'from': ('[frʌm]', '(介) 來自'),
    'front': ('[frʌnt]', '(名) 前面'),
    'fruit': ('[frust]', '(名) 水果'),
    'full': ('[fʊl]', '(形) 滿的'),
    'fun': ('[fʌn]', '(名) 樂趣'),
    'function': ('[ˈfʌŋkʃən]', '(名/動) 功能；起作用'),
    'funny': ('[ˈfʌni]', '(形) 有趣的'),
    'future': ('[ˈfjutʃɚ]', '(名) 未來'),
}

try:
    wb = openpyxl.load_workbook('2000voc.xlsx')
    ws = wb.active
    
    count = 0
    for row in range(2, ws.max_row + 1):
        word = ws[f'A{row}'].value
        if word and word.lower() in vocab_data:
            if not ws[f'B{row}'].value:
                phonetic, pos1 = vocab_data[word.lower()]
                ws[f'B{row}'] = phonetic
                ws[f'C{row}'] = pos1
                count += 1
    
    wb.save('2000voc.xlsx')
    print('Success: {} D-F words updated'.format(count))
    
except Exception as e:
    print('Error: {}'.format(str(e)))
