#!/usr/bin/env python
# -*- coding: utf-8 -*-
import openpyxl

# O-Z vocabulary data
vocab_data = {
    'object': ('[ˈɑbdʒɪkt]', '(名) 物體；目的'),
    'objective': ('[əbˈdʒɛktɪv]', '(形) 客觀的'),
    'obligation': ('[ˌɑbləˈɡeɪʃən]', '(名) 義務'),
    'oblige': ('[əˈblaɪdʒ]', '(動) 幫忙'),
    'observation': ('[ˌɑbzɚˈveɪʃən]', '(名) 觀察'),
    'observe': ('[əbˈzɜrv]', '(動) 觀察'),
    'observer': ('[əbˈzɜrvɚ]', '(名) 觀察者'),
    'obstacle': ('[ˈɑbstəkəl]', '(名) 障礙'),
    'obstinate': ('[ˈɑbstɪnət]', '(形) 固執的'),
    'obtain': ('[əbˈteɪn]', '(動) 獲得'),
    'obvious': ('[ˈɑbviəs]', '(形) 明顯的'),
    'occasion': ('[əˈkeɪʒən]', '(名) 場合'),
    'occasional': ('[əˈkeɪʒənəl]', '(形) 偶然的'),
    'occasionally': ('[əˈkeɪʒənəli]', '(副) 偶然'),
    'occupation': ('[ˌɑkjəˈpeɪʃən]', '(名) 職業'),
    'occupy': ('[ˈɑkjəˌpaɪ]', '(動) 佔據'),
    'occur': ('[əˈkɜr]', '(動) 發生'),
    'occurrence': ('[əˈkɜrəns]', '(名) 事件'),
    'ocean': ('[ˈoʊʃən]', '(名) 海洋'),
    'october': ('[ɑkˈtoʊbɚ]', '(名) 十月'),
    'odd': ('[ɑd]', '(形) 奇怪的；奇數的'),
    'odor': ('[ˈoʊdɚ]', '(名) 氣味'),
    'of': ('[əv]', '(介) 的'),
    'off': ('[ɔf]', '(副) 關閉'),
    'offence': ('[əˈfɛns]', '(名) 冒犯'),
    'offend': ('[əˈfɛnd]', '(動) 冒犯'),
    'offensive': ('[əˈfɛnsɪv]', '(形) 冒犯的'),
    'offer': ('[ˈɔfɚ]', '(動/名) 提供'),
    'office': ('[ˈɑfɪs]', '(名) 辦公室'),
    'officer': ('[ˈɑfɪsɚ]', '(名) 官員'),
    'official': ('[əˈfɪʃəl]', '(形) 官方的'),
    'often': ('[ˈɔfən]', '(副) 經常'),
    'oil': ('[ɔɪl]', '(名) 油'),
    'old': ('[oʊld]', '(形) 老的'),
    'older': ('[ˈoʊldɚ]', '(形) 更老的'),
    'oldest': ('[ˈoʊldəst]', '(形) 最老的'),
    'omit': ('[oʊˈmɪt]', '(動) 省略'),
    'on': ('[ɑn]', '(介) 在...上'),
    'once': ('[wʌns]', '(副) 一次'),
    'one': ('[wʌn]', '(數) 一'),
    'onion': ('[ˈʌnjən]', '(名) 洋蔥'),
    'only': ('[ˈoʊnli]', '(形/副) 唯一的'),
    'onset': ('[ˈɑnˌsɛt]', '(名) 開始'),
    'onto': ('[ˈɑntu]', '(介) 在...上面'),
    'onward': ('[ˈɑnwɚd]', '(副) 向前'),
    'onwards': ('[ˈɑnwɚdz]', '(副) 向前'),
    'open': ('[ˈoʊpən]', '(動/形) 打開；開放的'),
    'opening': ('[ˈoʊpənɪŋ]', '(名) 開口'),
    'opera': ('[ˈɑpərə]', '(名) 歌劇'),
    'operate': ('[ˈɑpəˌreɪt]', '(動) 操作'),
    'operation': ('[ˌɑpəˈreɪʃən]', '(名) 操作'),
    'operator': ('[ˈɑpəˌreɪtɚ]', '(名) 操作員'),
    'opinion': ('[əˈpɪnjən]', '(名) 看法'),
    'opponent': ('[əˈpoʊnənt]', '(名) 對手'),
    'opportunity': ('[ˌɑpɚˈtunəti]', '(名) 機會'),
    'oppose': ('[əˈpoʊz]', '(動) 反對'),
    'opposite': ('[ˈɑpəzɪt]', '(形) 相反的'),
    'opposition': ('[ˌɑpəˈzɪʃən]', '(名) 反對'),
    'oppress': ('[əˈprɛs]', '(動) 壓迫'),
    'oppression': ('[əˈprɛʃən]', '(名) 壓迫'),
    'oppressive': ('[əˈprɛsɪv]', '(形) 壓迫的'),
    'opt': ('[ɑpt]', '(動) 選擇'),
    'optical': ('[ˈɑptɪkəl]', '(形) 光學的'),
    'optimism': ('[ˈɑptɪˌmɪzəm]', '(名) 樂觀主義'),
    'optimistic': ('[ˌɑptɪˈmɪstɪk]', '(形) 樂觀的'),
    'option': ('[ˈɑpʃən]', '(名) 選項'),
    'optional': ('[ˈɑpʃənəl]', '(形) 可選的'),
    'or': ('[ɔr]', '(連) 或'),
    'oracle': ('[ˈɔrəkəl]', '(名) 神諭'),
    'oral': ('[ˈɔrəl]', '(形) 口頭的'),
    'orange': ('[ˈɔrɪndʒ]', '(名/形) 橘子；橙色'),
    'oration': ('[ɔˈreɪʃən]', '(名) 演說'),
    'orator': ('[ˈɔrətɚ]', '(名) 演說家'),
    'orbit': ('[ˈɔrbɪt]', '(名/動) 軌道'),
    'orchard': ('[ˈɔrtʃɚd]', '(名) 果園'),
    'orchestra': ('[ˈɔrkɪstrə]', '(名) 樂團'),
    'ordeal': ('[ɔrˈdil]', '(名) 考驗'),
    'order': ('[ˈɔrdɚ]', '(名/動) 順序；命令'),
    'orderly': ('[ˈɔrdɚli]', '(形) 有序的'),
    'ordinance': ('[ˈɔrdənəns]', '(名) 條令'),
    'ordinarily': ('[ɔrˈdɛnɛrəli]', '(副) 通常'),
    'ordinary': ('[ˈɔrdɪˌnɛri]', '(形) 普通的'),
    'organ': ('[ˈɔrɡən]', '(名) 器官；風琴'),
    'organic': ('[ɔrˈɡænɪk]', '(形) 有機的'),
    'organism': ('[ˈɔrɡənɪzəm]', '(名) 生物'),
    'organization': ('[ˌɔrɡənəˈzeɪʃən]', '(名) 組織'),
    'organize': ('[ˈɔrɡənˌaɪz]', '(動) 組織'),
    'organized': ('[ˈɔrɡənˌaɪzd]', '(形) 組織的'),
    'oriental': ('[ˌɔriˈɛntəl]', '(形) 東方的'),
    'orientation': ('[ˌɔriɛnˈteɪʃən]', '(名) 定向'),
    'origin': ('[ˈɔrɪdʒən]', '(名) 起源'),
    'original': ('[əˈrɪdʒənəl]', '(形) 原始的'),
    'originally': ('[əˈrɪdʒənəli]', '(副) 最初'),
    'originate': ('[əˈrɪdʒəˌneɪt]', '(動) 發源'),
    'ornament': ('[ˈɔrnəmənt]', '(名) 裝飾'),
    'ornamental': ('[ˌɔrnəˈmɛntəl]', '(形) 裝飾的'),
    'orphan': ('[ˈɔrfən]', '(名) 孤兒'),
    'ostrich': ('[ˈɑstrɪtʃ]', '(名) 鴕鳥'),
    'other': ('[ˈʌðɚ]', '(形) 其他的'),
    'otherwise': ('[ˈʌðɚˌwaɪz]', '(副) 否則'),
    'ought': ('[ɔt]', '(助) 應該'),
    'ounce': ('[aʊns]', '(名) 盎司'),
    'our': ('[aʊr]', '(代) 我們的'),
    'ours': ('[aʊrz]', '(代) 我們的'),
    'ourselves': ('[aʊrˈsɛlvz]', '(代) 我們自己'),
    'out': ('[aʊt]', '(副) 外面'),
    'outbreak': ('[ˈaʊtˌbreɪk]', '(名) 爆發'),
    'outcome': ('[ˈaʊtˌkʌm]', '(名) 結果'),
    'outdoor': ('[ˈaʊtˌdɔr]', '(形) 戶外的'),
    'outdoors': ('[ˌaʊtˈdɔrz]', '(副) 戶外'),
    'outer': ('[ˈaʊtɚ]', '(形) 外部的'),
    'outfit': ('[ˈaʊtˌfɪt]', '(名) 套裝'),
    'outing': ('[ˈaʊtɪŋ]', '(名) 郊遊'),
    'outlet': ('[ˈaʊtˌlɛt]', '(名) 出口'),
    'outline': ('[ˈaʊtˌlaɪn]', '(名/動) 輪廓'),
    'output': ('[ˈaʊtˌpʊt]', '(名) 產出'),
    'outrage': ('[ˈaʊtˌreɪdʒ]', '(名) 暴行'),
    'outrageous': ('[aʊtˈreɪdʒəs]', '(形) 令人髮指的'),
    'outset': ('[ˈaʊtˌsɛt]', '(名) 開始'),
    'outside': ('[ˌaʊtˈsaɪd]', '(介) 在...外面'),
    'outsider': ('[aʊtˈsaɪdɚ]', '(名) 局外人'),
    'outstanding': ('[aʊtˈstændɪŋ]', '(形) 傑出的'),
    'outward': ('[ˈaʊtwɚd]', '(形) 外向的'),
    'outwardly': ('[ˈaʊtwɚdli]', '(副) 表面上'),
    'outwit': ('[aʊtˈwɪt]', '(動) 欺騙'),
    'oval': ('[ˈoʊvəl]', '(形) 橢圓形的'),
    'ovary': ('[ˈoʊvəri]', '(名) 卵巢'),
    'oven': ('[ˈʌvən]', '(名) 烤箱'),
    'over': ('[ˈoʊvɚ]', '(介/副) 在...上方'),
    'overall': ('[ˌoʊvɚˈɔl]', '(形) 全面的'),
    'overalls': ('[ˈoʊvɚˌɔlz]', '(名) 工作褲'),
    'overawe': ('[ˌoʊvɚˈɔ]', '(動) 使敬畏'),
    'overbalance': ('[ˌoʊvɚˈbæləns]', '(動) 失衡'),
    'overbearing': ('[ˌoʊvɚˈbɛrɪŋ]', '(形) 傲慢的'),
    'overboard': ('[ˌoʊvɚˈbɔrd]', '(副) 落水'),
    'overcast': ('[ˌoʊvɚˈkæst]', '(形) 陰沉的'),
    'overcome': ('[ˌoʊvɚˈkʌm]', '(動) 克服'),
    'overflow': ('[ˌoʊvɚˈfloʊ]', '(動/名) 溢出'),
    'overhang': ('[ˌoʊvɚˈhæŋ]', '(動) 懸伸'),
    'overhead': ('[ˌoʊvɚˈhɛd]', '(形/副) 在頭上'),
    'overhear': ('[ˌoʊvɚˈhɪr]', '(動) 無意中聽到'),
    'overjoy': ('[ˌoʊvɚˈdʒɔɪ]', '(動) 使狂喜'),
    'overlap': ('[ˌoʊvɚˈlæp]', '(動) 重疊'),
    'overlook': ('[ˌoʊvɚˈlʊk]', '(動) 忽視'),
    'overlord': ('[ˈoʊvɚˌlɔrd]', '(名) 主人'),
    'overnight': ('[ˌoʊvɚˈnaɪt]', '(形) 一夜之間'),
    'overpower': ('[ˌoʊvɚˈpaʊɚ]', '(動) 壓倒'),
    'overpowering': ('[ˌoʊvɚˈpaʊərɪŋ]', '(形) 壓倒性的'),
    'overrate': ('[ˌoʊvɚˈreɪt]', '(動) 高估'),
    'override': ('[ˌoʊvɚˈraɪd]', '(動) 推翻'),
    'overrule': ('[ˌoʊvɚˈrul]', '(動) 否決'),
    'overrun': ('[ˌoʊvɚˈrʌn]', '(動) 超出'),
    'overseas': ('[ˌoʊvɚˈsiz]', '(形/副) 海外的'),
    'oversee': ('[ˌoʊvɚˈsi]', '(動) 監督'),
    'overseer': ('[ˌoʊvɚˈsiɚ]', '(名) 監督員'),
    'overshadow': ('[ˌoʊvɚˈʃædoʊ]', '(動) 遮蔽'),
    'overshoe': ('[ˈoʊvɚˌʃu]', '(名) 高筒鞋'),
    'oversight': ('[ˈoʊvɚˌsaɪt]', '(名) 監督'),
    'oversleep': ('[ˌoʊvɚˈslip]', '(動) 睡過'),
    'overstate': ('[ˌoʊvɚˈsteɪt]', '(動) 誇大'),
    'overstatement': ('[ˌoʊvɚˈsteɪtmənt]', '(名) 誇大'),
    'overstep': ('[ˌoʊvɚˈstɛp]', '(動) 超越'),
    'overt': ('[oʊˈvɜrt]', '(形) 公開的'),
    'overtake': ('[ˌoʊvɚˈteɪk]', '(動) 超過'),
    'overthrow': ('[ˌoʊvɚˈθroʊ]', '(動) 推翻'),
    'overtime': ('[ˈoʊvɚˌtaɪm]', '(名) 加班'),
    'overtone': ('[ˈoʊvɚˌtoʊn]', '(名) 暗示'),
    'overtop': ('[ˌoʊvɚˈtɑp]', '(動) 超過'),
    'overture': ('[ˈoʊvɚˌtʃur]', '(名) 序曲'),
    'overturn': ('[ˌoʊvɚˈtɜrn]', '(動) 推翻'),
    'overview': ('[ˈoʊvɚˌvju]', '(名) 概覽'),
    'overwhelming': ('[ˌoʊvɚˈwɛlmɪŋ]', '(形) 壓倒性的'),
    'overwhelmingly': ('[ˌoʊvɚˈwɛlmɪŋli]', '(副) 壓倒性地'),
    'overwhelm': ('[ˌoʊvɚˈwɛlm]', '(動) 使不知所措'),
    'owes': ('[oʊz]', '(動) 欠'),
    'owing': ('[ˈoʊɪŋ]', '(形) 應付的'),
    'owl': ('[aʊl]', '(名) 貓頭鷹'),
    'own': ('[oʊn]', '(動) 擁有'),
    'owner': ('[ˈoʊnɚ]', '(名) 主人'),
    'ownership': ('[ˈoʊnɚʃɪp]', '(名) 所有權'),
    'ox': ('[ɑks]', '(名) 牛'),
    'oxygen': ('[ˈɑksɪdʒən]', '(名) 氧氣'),
    'oyster': ('[ˈɔɪstɚ]', '(名) 牡蠣'),
    'ozone': ('[ˈoʊˌzoʊn]', '(名) 臭氧'),
}

try:
    wb = openpyxl.load_workbook('2000voc.xlsx')
    ws = wb.active
    
    count = 0
    for row in range(2, ws.max_row + 1):
        word = ws[f'A{row}'].value
        if word and word.lower() in vocab_data:
            if not ws[f'B{row}'].value:
                phonetic, pos1 = vocab_data[word.lower()]
                ws[f'B{row}'] = phonetic
                ws[f'C{row}'] = pos1
                count += 1
    
    wb.save('2000voc.xlsx')
    print('Success: {} O words updated'.format(count))
    
except Exception as e:
    print('Error: {}'.format(str(e)))
