#!/usr/bin/env python
# -*- coding: utf-8 -*-
import openpyxl

# G-Z vocabulary data
vocab_data = {
    'gain': ('[ɡeɪn]', '(動/名) 獲得'),
    'game': ('[ɡeɪm]', '(名) 遊戲'),
    'garage': ('[ɡəˈrɑʒ]', '(名) 車庫'),
    'garbage': ('[ˈɡɑrbɪdʒ]', '(名) 垃圾'),
    'garden': ('[ˈɡɑrdən]', '(名) 花園'),
    'gas': ('[ɡæs]', '(名) 氣體；汽油'),
    'gather': ('[ˈɡæðɚ]', '(動) 聚集'),
    'general': ('[ˈdʒɛnərəl]', '(形) 一般的'),
    'generous': ('[ˈdʒɛnərəs]', '(形) 慷慨的'),
    'gentleman': ('[ˈdʒɛntəlmən]', '(名) 紳士'),
    'geography': ('[dʒiˈɑɡrəfi]', '(名) 地理'),
    'get': ('[ɡɛt]', '(動) 得到'),
    'ghost': ('[ɡoʊst]', '(名) 鬼'),
    'giant': ('[ˈdʒaɪənt]', '(名) 巨人'),
    'gift': ('[ɡɪft]', '(名) 禮物'),
    'girl': ('[ɡɜrl]', '(名) 女孩'),
    'give': ('[ɡɪv]', '(動) 給予'),
    'glad': ('[ɡlæd]', '(形) 高興的'),
    'glass': ('[ɡlæs]', '(名) 玻璃；杯子'),
    'glue': ('[ɡlu]', '(名) 膠水'),
    'go': ('[ɡoʊ]', '(動) 去'),
    'goal': ('[ɡoʊl]', '(名) 目標'),
    'god': ('[ɡɑd]', '(名) 上帝'),
    'gold': ('[ɡoʊld]', '(名) 黃金'),
    'good': ('[ɡʊd]', '(形) 好的'),
    'government': ('[ˈɡʌvɚnmənt]', '(名) 政府'),
    'grade': ('[ɡreɪd]', '(名) 年級；成績'),
    'grain': ('[ɡreɪn]', '(名) 穀物'),
    'grandfather': ('[ˈɡrænˌfɑðɚ]', '(名) 祖父'),
    'grandmother': ('[ˈɡrænˌmʌðɚ]', '(名) 祖母'),
    'grandson': ('[ˈɡrænˌsʌn]', '(名) 孫子'),
    'grape': ('[ɡreɪp]', '(名) 葡萄'),
    'grass': ('[ɡræs]', '(名) 草'),
    'grateful': ('[ˈɡreɪtfəl]', '(形) 感謝的'),
    'great': ('[ɡreɪt]', '(形) 偉大的'),
    'green': ('[ɡrin]', '(形) 綠色的'),
    'group': ('[ɡrup]', '(名) 組'),
    'grow': ('[ɡroʊ]', '(動) 成長'),
    'guess': ('[ɡɛs]', '(動/名) 猜測'),
    'guest': ('[ɡɛst]', '(名) 客人'),
    'guide': ('[ɡaɪd]', '(動/名) 指南；引導'),
    'gun': ('[ɡʌn]', '(名) 槍'),
    'habit': ('[ˈhæbɪt]', '(名) 習慣'),
    'hair': ('[hɛr]', '(名) 頭髮'),
    'half': ('[hæf]', '(名) 一半'),
    'hand': ('[hænd]', '(名) 手'),
    'happen': ('[ˈhæpən]', '(動) 發生'),
    'happiness': ('[ˈhæpinəs]', '(名) 幸福'),
    'happy': ('[ˈhæpi]', '(形) 快樂的'),
    'hard': ('[hɑrd]', '(形) 硬的；困難的'),
    'hardly': ('[ˈhɑrdli]', '(副) 幾乎不'),
    'harm': ('[hɑrm]', '(動/名) 傷害'),
    'hat': ('[hæt]', '(名) 帽子'),
    'hate': ('[heɪt]', '(動) 討厭'),
    'have': ('[hæv]', '(動) 有'),
    'head': ('[hɛd]', '(名) 頭'),
    'health': ('[hɛlθ]', '(名) 健康'),
    'healthy': ('[ˈhɛlθi]', '(形) 健康的'),
    'hear': ('[hɪr]', '(動) 聽'),
    'heart': ('[hɑrt]', '(名) 心臟'),
    'heat': ('[hit]', '(名/動) 熱'),
    'heavy': ('[ˈhɛvi]', '(形) 重的'),
    'height': ('[haɪt]', '(名) 高度'),
    'help': ('[hɛlp]', '(動/名) 幫助'),
    'helpful': ('[ˈhɛlpfəl]', '(形) 有幫助的'),
    'here': ('[hɪr]', '(副) 這裡'),
    'hero': ('[ˈhɪroʊ]', '(名) 英雄'),
    'high': ('[haɪ]', '(形) 高的'),
    'hill': ('[hɪl]', '(名) 山丘'),
    'him': ('[hɪm]', '(代) 他'),
    'himself': ('[hɪmˈsɛlf]', '(代) 他自己'),
    'history': ('[ˈhɪstəri]', '(名) 歷史'),
    'hit': ('[hɪt]', '(動) 打擊'),
    'hobby': ('[ˈhɑbi]', '(名) 愛好'),
    'hold': ('[hoʊld]', '(動) 握著'),
    'hole': ('[hoʊl]', '(名) 洞'),
    'holiday': ('[ˈhɑləˌdeɪ]', '(名) 假日'),
    'home': ('[hoʊm]', '(名) 家'),
    'homework': ('[ˈhoʊmˌwɜrk]', '(名) 功課'),
    'honest': ('[ˈɑnɪst]', '(形) 誠實的'),
    'hope': ('[hoʊp]', '(動/名) 希望'),
    'horse': ('[hɔrs]', '(名) 馬'),
    'hospital': ('[ˈhɑspɪtəl]', '(名) 醫院'),
    'host': ('[hoʊst]', '(名) 主人'),
    'hot': ('[hɑt]', '(形) 熱的'),
    'hotel': ('[hoʊˈtɛl]', '(名) 旅館'),
    'hour': ('[aʊɚ]', '(名) 小時'),
    'house': ('[haʊs]', '(名) 房子'),
    'how': ('[haʊ]', '(副) 如何'),
    'however': ('[haʊˈɛvɚ]', '(副) 然而'),
    'huge': ('[hjudʒ]', '(形) 巨大的'),
    'human': ('[ˈhjumən]', '(形/名) 人的；人'),
    'humor': ('[ˈhjumɚ]', '(名) 幽默'),
    'hundred': ('[ˈhʌndrəd]', '(數) 百'),
    'hungry': ('[ˈhʌŋɡri]', '(形) 饑餓的'),
    'hunt': ('[hʌnt]', '(動) 獵取'),
    'hurry': ('[ˈhɜri]', '(動) 匆忙'),
    'hurt': ('[hɜrt]', '(動) 傷害'),
    'husband': ('[ˈhʌzbənd]', '(名) 丈夫'),
    'ice': ('[aɪs]', '(名) 冰'),
    'idea': ('[aɪˈdiə]', '(名) 想法'),
    'identify': ('[aɪˈdɛntəˌfaɪ]', '(動) 辨認'),
    'if': ('[ɪf]', '(連) 如果'),
    'ignore': ('[ɪɡˈnɔr]', '(動) 忽視'),
    'ill': ('[ɪl]', '(形) 有病的'),
    'illness': ('[ˈɪlnəs]', '(名) 疾病'),
    'image': ('[ˈɪmɪdʒ]', '(名) 圖像'),
    'imagine': ('[ɪˈmædʒən]', '(動) 想像'),
    'immediate': ('[ɪˈmidiət]', '(形) 立即的'),
    'immediately': ('[ɪˈmidiətli]', '(副) 立即'),
    'import': ('[ɪmˈpɔrt]', '(動) 進口'),
    'importance': ('[ɪmˈpɔrtəns]', '(名) 重要性'),
    'important': ('[ɪmˈpɔrtənt]', '(形) 重要的'),
    'impossible': ('[ɪmˈpɑsəbəl]', '(形) 不可能的'),
    'improve': ('[ɪmˈpruv]', '(動) 改善'),
    'improvement': ('[ɪmˈpruvmənt]', '(名) 改善'),
    'in': ('[ɪn]', '(介) 在...內'),
    'incident': ('[ˈɪnsɪdənt]', '(名) 事件'),
    'include': ('[ɪnˈklud]', '(動) 包括'),
    'income': ('[ˈɪnˌkʌm]', '(名) 收入'),
    'increase': ('[ɪnˈkris]', '(動/名) 增加'),
    'indeed': ('[ɪnˈdid]', '(副) 確實'),
    'independent': ('[ˌɪndɪˈpɛndənt]', '(形) 獨立的'),
    'indicate': ('[ˈɪndɪˌkeɪt]', '(動) 表明'),
    'industry': ('[ˈɪndəstri]', '(名) 工業'),
    'influence': ('[ˈɪnfluəns]', '(動/名) 影響'),
    'information': ('[ˌɪnfɚˈmeɪʃən]', '(名) 信息'),
    'injury': ('[ˈɪndʒəri]', '(名) 傷害'),
    'inside': ('[ɪnˈsaɪd]', '(介) 在...內部'),
    'instead': ('[ɪnˈstɛd]', '(副) 代替'),
    'instruction': ('[ɪnˈstrʌkʃən]', '(名) 教導'),
    'instrument': ('[ˈɪnstrəmənt]', '(名) 樂器；工具'),
    'insult': ('[ˈɪnsʌlt]', '(動/名) 侮辱'),
    'insurance': ('[ɪnˈʃʊrəns]', '(名) 保險'),
    'intelligent': ('[ɪnˈtɛlɪdʒənt]', '(形) 聰明的'),
    'intend': ('[ɪnˈtɛnd]', '(動) 打算'),
    'interest': ('[ˈɪntərəst]', '(名/動) 興趣'),
    'interested': ('[ˈɪntərəstəd]', '(形) 感興趣的'),
    'interesting': ('[ˈɪntərəstɪŋ]', '(形) 有趣的'),
    'internal': ('[ɪnˈtɜrnəl]', '(形) 內部的'),
    'international': ('[ˌɪntɚˈnæʃənəl]', '(形) 國際的'),
    'into': ('[ˈɪntu]', '(介) 進入'),
    'introduce': ('[ˌɪntrəˈdus]', '(動) 介紹'),
    'introduction': ('[ˌɪntrəˈdʌkʃən]', '(名) 介紹'),
    'invent': ('[ɪnˈvɛnt]', '(動) 發明'),
    'invention': ('[ɪnˈvɛnʃən]', '(名) 發明'),
    'invest': ('[ɪnˈvɛst]', '(動) 投資'),
    'investment': ('[ɪnˈvɛstmənt]', '(名) 投資'),
    'invitation': ('[ˌɪnvɪˈteɪʃən]', '(名) 邀請'),
    'invite': ('[ɪnˈvaɪt]', '(動) 邀請'),
    'involve': ('[ɪnˈvɑlv]', '(動) 涉及'),
    'iron': ('[ˈaɪɚn]', '(名) 鐵'),
    'island': ('[ˈaɪlənd]', '(名) 島嶼'),
    'issue': ('[ˈɪʃu]', '(名) 問題'),
    'it': ('[ɪt]', '(代) 它'),
    'item': ('[ˈaɪtəm]', '(名) 項目'),
    'itself': ('[ɪtˈsɛlf]', '(代) 它自己'),
}

try:
    wb = openpyxl.load_workbook('2000voc.xlsx')
    ws = wb.active
    
    count = 0
    for row in range(2, ws.max_row + 1):
        word = ws[f'A{row}'].value
        if word and word.lower() in vocab_data:
            if not ws[f'B{row}'].value:
                phonetic, pos1 = vocab_data[word.lower()]
                ws[f'B{row}'] = phonetic
                ws[f'C{row}'] = pos1
                count += 1
    
    wb.save('2000voc.xlsx')
    print('Success: {} G-I words updated'.format(count))
    
except Exception as e:
    print('Error: {}'.format(str(e)))
