import openpyxl

qz_vocab = {
    # Q words
    'quack': '[kwæk]', 'quad': '[kwɑd]', 'quadrant': '[ˈkwɑdrənt]', 'quadratic': '[kwɑˈdrætɪk]', 'quadrature': '[ˈkwɑdrətʃɚ]',
    'quadrennial': '[kwɑˈdrɛniəl]', 'quadriceps': '[ˈkwɑdrɪˌsɛps]', 'quadrilateral': '[ˌkwɑdrɪˈlætərəl]', 'quadrille': '[kwɑˈdril]', 'quadrillion': '[kwɑˈdrɪljən]',
    'quadripartite': '[kwɑdrɪˈpɑrtaɪt]', 'quadrireme': '[ˈkwɑdrɪˌrim]', 'quadrivium': '[kwɑˈdrɪviəm]', 'quadroon': '[kwɑˈdrun]', 'quadruped': '[ˈkwɑdruˌpɛd]',
    'quadrupedal': '[kwɑˈdrupədəl]', 'quadruple': '[kwɑˈdrupəl]', 'quadruplet': '[kwɑˈdrupɪt]', 'quadruplex': '[kwɑˈdrupɪks]', 'quadruplicate': '[kwɑˈduplɪˌkeɪt]',
    'quaere': '[ˈkwiri]', 'quaff': '[kwæf]', 'quagga': '[ˈkwæɡə]', 'quagga': '[ˈkwæɡə]', 'quaggy': '[ˈkwæɡi]',
    'quagmire': '[ˈkwæɡˌmaɪr]', 'quahog': '[ˈkwoʊˌhɑɡ]', 'quail': '[kweɪl]', 'quaint': '[kweɪnt]', 'quake': '[kweɪk]',
    'quaker': '[ˈkweɪkɚ]', 'quaking': '[ˈkweɪkɪŋ]', 'qualifiable': '[ˈkwɑləˌfaɪəbəl]', 'qualification': '[ˌkwɑləfɪˈkeɪʃən]', 'qualifier': '[ˈkwɑləˌfaɪɚ]',
    'qualify': '[ˈkwɑləˌfaɪ]', 'qualifying': '[ˈkwɑləˌfaɪɪŋ]', 'qualitative': '[ˈkwɑlɪˌteɪtɪv]', 'qualitatively': '[ˈkwɑlɪˌteɪtɪvli]', 'quality': '[ˈkwɑləti]',
    'qualm': '[kwɑm]', 'qualmish': '[ˈkwɑmɪʃ]', 'quandary': '[ˈkwɑnderi]', 'quanta': '[ˈkwɑntə]', 'quantifiable': '[ˌkwɑntɪˈfaɪəbəl]',
    'quantification': '[ˌkwɑntɪfɪˈkeɪʃən]', 'quantifier': '[ˈkwɑntɪˌfaɪɚ]', 'quantify': '[ˈkwɑntɪˌfaɪ]', 'quantitative': '[ˈkwɑntɪˌteɪtɪv]', 'quantitatively': '[ˈkwɑntɪˌteɪtɪvli]',
    'quantity': '[ˈkwɑntɪti]', 'quantization': '[ˌkwɑntɪˈzeɪʃən]', 'quantize': '[ˈkwɑntaɪz]', 'quantum': '[ˈkwɑntəm]', 'quark': '[kwɑrk]',
    'quarantine': '[ˈkwɔrənˌtin]', 'quarantined': '[ˈkwɔrənˌtind]', 'quarantining': '[ˈkwɔrənˌtinɪŋ]', 'quark': '[kwɑrk]', 'quarrel': '[ˈkwɔrəl]',
    'quarreled': '[ˈkwɔrəld]', 'quarreling': '[ˈkwɔrəlɪŋ]', 'quarrelsome': '[ˈkwɔrəlsəm]', 'quarrelsomely': '[ˈkwɔrəlsəmli]', 'quarrelsome': '[ˈkwɔrəlsəm]',
    'quarried': '[ˈkwɔrid]', 'quarrier': '[ˈkwɔriɚ]', 'quarries': '[ˈkwɔriz]', 'quarry': '[ˈkwɔri]', 'quarrying': '[ˈkwɔriɪŋ]',
    'quart': '[kwɔrt]', 'quarter': '[ˈkwɔrtɚ]', 'quarterback': '[ˈkwɔrtɚˌbæk]', 'quarterdeck': '[ˈkwɔrtɚˌdɛk]', 'quartered': '[ˈkwɔrtɚd]',
    'quartering': '[ˈkwɔrtərɪŋ]', 'quarterfinal': '[ˌkwɔrtɚˈfaɪnəl]', 'quarterfinals': '[ˌkwɔrtɚˈfaɪnəlz]', 'quarterfinalist': '[ˌkwɔrtɚˈfaɪnəlɪst]', 'quarterfinalists': '[ˌkwɔrtɚˈfaɪnəlɪsts]',
    'quarterbacks': '[ˈkwɔrtɚˌbæks]', 'quarterly': '[ˈkwɔrtɚli]', 'quartermaster': '[ˈkwɔrtɚˌmæstɚ]', 'quartermasters': '[ˈkwɔrtɚˌmæstɚz]', 'quarters': '[ˈkwɔrtɚz]',
    'quarterstaff': '[ˈkwɔrtɚˌstæf]', 'quarterstaffs': '[ˈkwɔrtɚˌstæfs]', 'quartet': '[kwɔrˈtɛt]', 'quartette': '[kwɔrˈtɛt]', 'quartets': '[kwɔrˈtɛts]',
    'quartile': '[ˈkwɔrˌtaɪl]', 'quartiles': '[ˈkwɔrˌtaɪlz]', 'quarto': '[ˈkwɔrtoʊ]', 'quartos': '[ˈkwɔrˌtoʊz]', 'quartz': '[kwɔrts]',
    'quartzes': '[ˈkwɔrtsɪz]', 'quartzite': '[ˈkwɔrtˌsaɪt]', 'quasar': '[ˈkweɪˌzɑr]', 'quasars': '[ˈkweɪˌzɑrz]', 'quash': '[kwɑʃ]',
    'quashed': '[kwɑʃt]', 'quashes': '[ˈkwɑʃɪz]', 'quashing': '[ˈkwɑʃɪŋ]', 'quasi': '[ˈkweɪˌzaɪ]', 'quass': '[kwæs]',
    'quatern': '[ˈkweɪtɚn]', 'quaternary': '[kwəˈtɜrneri]', 'quaternion': '[kwəˈtɜrnjən]', 'quatorzain': '[kwɑtɔrˈzeɪn]', 'quatrain': '[ˈkwɑtrən]',
    'quatrains': '[ˈkwɑtrənz]', 'quatre': '[ˈkwætrə]', 'quatrefoil': '[ˈkwætrəˌfɔɪl]', 'quatrefoils': '[ˈkwætrəˌfɔɪlz]', 'quaver': '[ˈkweɪvɚ]',
    'quavered': '[ˈkweɪvɚd]', 'quavering': '[ˈkweɪvərɪŋ]', 'quaveringly': '[ˈkweɪvərɪŋli]', 'quavers': '[ˈkweɪvɚz]', 'quay': '[ki]',
    'quays': '[kiz]', 'quayage': '[ˈkiɪdʒ]', 'queach': '[kwitʃ]', 'queachy': '[ˈkwitʃi]', 'queasily': '[ˈkwizɪli]',
    'queasiness': '[ˈkwizinɪs]', 'queasy': '[ˈkwizi]', 'queazy': '[ˈkwizi]',
    # R words (selected high frequency)
    'rabbit': '[ˈræbɪt]', 'race': '[reɪs]', 'radar': '[ˈreɪˌdɑr]', 'radiant': '[ˈreɪdiənt]', 'radiate': '[ˈreɪdiˌeɪt]',
    'radiation': '[ˌreɪdiˈeɪʃən]', 'radiator': '[ˈreɪdiˌeɪtɚ]', 'radical': '[ˈrædɪkəl]', 'radio': '[ˈreɪdioʊ]', 'radioactive': '[ˌreɪdioʊˈæktɪv]',
    'radius': '[ˈreɪdiəs]', 'raft': '[ræft]', 'rafter': '[ˈræftɚ]', 'rag': '[ræɡ]', 'rage': '[reɪdʒ]',
    'raid': '[reɪd]', 'rail': '[reɪl]', 'railroad': '[ˈreɪlˌroʊd]', 'railway': '[ˈreɪlˌweɪ]', 'rain': '[reɪn]',
    'rainbow': '[ˈreɪnˌboʊ]', 'rainfall': '[ˈreɪnˌfɔl]', 'rainy': '[ˈreɪni]', 'raise': '[reɪz]', 'raisin': '[ˈreɪzən]',
    'rake': '[reɪk]', 'rally': '[ˈræli]', 'ram': '[ræm]', 'ramble': '[ˈræmbəl]', 'rampage': '[ˈræmˌpeɪdʒ]',
    'rampant': '[ˈræmpənt]', 'rampart': '[ˈræmˌpɑrt]', 'rampike': '[ˈræmˌpaɪk]', 'ramrod': '[ˈræmˌrɑd]', 'ramshackle': '[ˈræmˌʃækəl]',
    'ran': '[ræn]', 'ranch': '[ræntʃ]', 'rancher': '[ˈræntʃɚ]', 'rancid': '[ˈrænsɪd]', 'rancidity': '[ræn ˈsɪdɪti]',
    'rancor': '[ˈræŋkɚ]', 'rancorous': '[ˈræŋkərəs]', 'random': '[ˈrændəm]', 'randomly': '[ˈrændəmli]', 'randomness': '[ˈrændəmnɪs]',
    'randy': '[ˈrændi]', 'rang': '[ræŋ]', 'range': '[reɪndʒ]', 'ranger': '[ˈreɪndʒɚ]', 'rangy': '[ˈreɪndʒi]',
    'rani': '[ˈrɑni]', 'rank': '[ræŋk]', 'ranker': '[ˈræŋkɚ]', 'rankle': '[ˈræŋkəl]', 'rankled': '[ˈræŋkəld]',
    'ransack': '[ˈrænˌsæk]', 'ransom': '[ˈrænsəm]', 'ransomed': '[ˈrænsəmd]', 'ransoming': '[ˈrænsəmɪŋ]', 'rant': '[rænt]',
    'rap': '[ræp]', 'rapacious': '[rəˈpeɪʃəs]', 'rapaciously': '[rəˈpeɪʃəsli]', 'rapacity': '[rəˈpæsɪti]', 'rape': '[reɪp]',
    'rapid': '[ˈræpɪd]', 'rapidity': '[rəˈpɪdɪti]', 'rapidly': '[ˈræpɪdli]', 'rapids': '[ˈræpɪdz]', 'rapier': '[ˈreɪpiɚ]',
    'rapine': '[ˈræpɪn]', 'rapper': '[ˈræpɚ]', 'rapport': '[ræˈpɔr]', 'rapprochement': '[ˌræprɔʃˈmɑn]', 'rapscallion': '[ræpˈskæljən]',
    'rapt': '[ræpt]', 'raptor': '[ˈræptɚ]', 'raptorial': '[ræpˈtɔriəl]', 'rapture': '[ˈræptʃɚ]', 'rapturously': '[ˈræptʃərəsli]',
    'rare': '[rɛr]', 'rarely': '[ˈrɛrli]', 'rareness': '[ˈrɛrnɪs]', 'rarefy': '[ˈrɛrəˌfaɪ]', 'rarefied': '[ˈrɛrəˌfaɪd]',
    'rarity': '[ˈrɛrɪti]', 'rascal': '[ˈræskəl]', 'rascality': '[ræsˈkæləti]', 'rascallion': '[ræsˈkæljən]', 'rascally': '[ˈræskəli]',
    'rash': '[ræʃ]', 'rasher': '[ˈræʃɚ]', 'rashly': '[ˈræʃli]', 'rashness': '[ˈræʃnɪs]', 'rasp': '[ræsp]',
    'rasped': '[ræspt]', 'rasper': '[ˈræspɚ]', 'raspily': '[ˈræspɪli]', 'rasping': '[ˈræspɪŋ]', 'raspingly': '[ˈræspɪŋli]',
    'raspberry': '[ˈræzˌbɛri]', 'raspy': '[ˈræspi]', 'rat': '[ræt]', 'ratan': '[ˈrætən]', 'ratch': '[rætʃ]',
    'ratchet': '[ˈrætʃɪt]', 'rate': '[reɪt]', 'rated': '[ˈreɪtɪd]', 'rater': '[ˈreɪtɚ]', 'rather': '[ˈræðɚ]',
    'ratify': '[ˈrætɪˌfaɪ]', 'ratifying': '[ˈrætɪˌfaɪɪŋ]', 'rating': '[ˈreɪtɪŋ]', 'ratio': '[ˈreɪʃoʊ]', 'ration': '[ˈræʃən]',
    'rational': '[ˈræʃənəl]', 'rationale': '[ˌræʃəˈnæl]', 'rationality': '[ˌræʃəˈnæləti]', 'rationalization': '[ˌræʃənəlɪˈzeɪʃən]', 'rationalize': '[ˈræʃənəˌlaɪz]',
    'rationally': '[ˈræʃənəli]', 'rationed': '[ˈræʃənd]', 'rationing': '[ˈræʃənɪŋ]', 'ratline': '[ˈrætˌlin]', 'rattan': '[ˈrætən]',
    'rattle': '[ˈrætəl]', 'rattled': '[ˈrætəld]', 'rattler': '[ˈrætlɚ]', 'rattlesnake': '[ˈrætəlˌsneɪk]', 'rattling': '[ˈrætəlɪŋ]',
    'ratty': '[ˈræti]', 'raucous': '[ˈrɔkəs]', 'raucously': '[ˈrɔkəsli]', 'raucousness': '[ˈrɔkəsnɪs]', 'ravage': '[ˈrævɪdʒ]',
    'ravaged': '[ˈrævɪdʒd]', 'ravager': '[ˈrævɪdʒɚ]', 'ravages': '[ˈrævɪdʒɪz]', 'ravaging': '[ˈrævɪdʒɪŋ]', 'rave': '[reɪv]',
    'raved': '[reɪvd]', 'ravel': '[ˈrævəl]', 'raveled': '[ˈrævəld]', 'raveling': '[ˈrævəlɪŋ]', 'raven': '[ˈreɪvən]',
    'ravening': '[ˈreɪvənɪŋ]', 'ravenous': '[ˈrævənəs]', 'ravenously': '[ˈrævənəsli]', 'ravenousness': '[ˈrævənəsnɪs]', 'ravens': '[ˈreɪvənz]',
    'raver': '[ˈreɪvɚ]', 'ravine': '[rəˈvin]', 'ravine': '[rəˈvin]', 'raving': '[ˈreɪvɪŋ]', 'ravings': '[ˈreɪvɪŋz]',
    'ravioli': '[ˌrɑviˈoʊli]', 'ravish': '[ˈrævɪʃ]', 'ravished': '[ˈrævɪʃt]', 'ravisher': '[ˈrævɪʃɚ]', 'ravishing': '[ˈrævɪʃɪŋ]',
    'ravishingly': '[ˈrævɪʃɪŋli]', 'ravishment': '[ˈrævɪʃmənt]', 'ravishments': '[ˈrævɪʃmənts]', 'raw': '[rɔ]', 'rawer': '[ˈrɔɚ]',
    'rawest': '[ˈrɔɪst]', 'rawhide': '[ˈrɔˌhaɪd]', 'rawly': '[ˈrɔli]', 'rawness': '[ˈrɔnɪs]', 'ray': '[reɪ]',
    'rays': '[reɪz]', 'rayon': '[ˈreɪɑn]', 'rayons': '[ˈreɪɑnz]', 'raze': '[reɪz]', 'razed': '[reɪzd]',
    'razing': '[ˈreɪzɪŋ]', 'razor': '[ˈreɪzɚ]', 'razorback': '[ˈreɪzɚˌbæk]', 'razorbill': '[ˈreɪzɚˌbɪl]', 'razors': '[ˈreɪzɚz]',
    'razz': '[ræz]', 'razzed': '[ræzd]', 'razzes': '[ˈræzɪz]', 'razzing': '[ˈræzɪŋ]', 'razzle': '[ˈræzəl]',
    'razzledazzle': '[ˈræzəlˌdæzəl]', 'razzy': '[ˈræzi]',
    # S words (selected high frequency)
    'sabai': '[səˈbaɪ]', 'sabbat': '[ˈsæbət]', 'sabbath': '[ˈsæbəθ]', 'sabbathless': '[ˈsæbəθlɪs]', 'sabbaths': '[ˈsæbəθz]',
    'sabbatic': '[səˈbætɪk]', 'sabbatical': '[səˈbætɪkəl]', 'sabbaticals': '[səˈbætɪkəlz]', 'saber': '[ˈseɪbɚ]', 'sabered': '[ˈseɪbɚd]',
    'sabering': '[ˈseɪbərɪŋ]', 'sabers': '[ˈseɪbɚz]', 'sable': '[ˈseɪbəl]', 'sables': '[ˈseɪbəlz]', 'sabot': '[ˈsæboʊ]',
    'sabotage': '[ˌsæbəˈtɑʒ]', 'sabotaged': '[ˌsæbəˈtɑʒd]', 'sabotages': '[ˌsæbəˈtɑʒɪz]', 'sabotaging': '[ˌsæbəˈtɑʒɪŋ]', 'saboteur': '[ˌsæbəˈtɜr]',
    'saboteurs': '[ˌsæbəˈtɜrz]', 'sabots': '[ˈsæboʊz]', 'sabre': '[ˈseɪbɚ]', 'sabres': '[ˈseɪbɚz]', 'sac': '[sæk]',
    'saccade': '[sæˈkɑd]', 'saccadic': '[sæˈkædɪk]', 'saccharin': '[ˈsækərɪn]', 'saccharine': '[ˈsækəˌrin]', 'saccharinity': '[ˌsækəˈrɪnɪti]',
    'saccharoid': '[ˈsækəˌrɔɪd]', 'saccharose': '[ˈsækəˌroʊs]', 'saccharum': '[ˈsækərəm]', 'saccular': '[ˈsækjələr]', 'sacculate': '[ˈsækjəˌleɪt]',
    'saccule': '[ˈsækjul]', 'sacerdotal': '[ˌsæsɚˈdoʊtəl]', 'sacerdotalism': '[ˌsæsɚˈdoʊtəˌlɪzəm]', 'sacerdotally': '[ˌsæsɚˈdoʊtəli]', 'sachem': '[ˈseɪtʃəm]',
    'sachems': '[ˈseɪtʃəmz]', 'sachet': '[sæˈʃeɪ]', 'sack': '[sæk]', 'sackbut': '[ˈsækbət]', 'sacked': '[sækt]',
    'sacker': '[ˈsækɚ]', 'sacking': '[ˈsækɪŋ]', 'sackings': '[ˈsækɪŋz]', 'sacks': '[sæks]', 'sacque': '[sæk]',
    'sacral': '[ˈseɪkrəl]', 'sacrament': '[ˈsækrəmənt]', 'sacramental': '[ˌsækrəˈmɛntəl]', 'sacramentalism': '[ˌsækrəˈmɛntəˌlɪzəm]', 'sacramentally': '[ˌsækrəˈmɛntəli]',
    'sacraments': '[ˈsækrəmənts]', 'sacred': '[ˈseɪkrɪd]', 'sacredly': '[ˈseɪkrɪdli]', 'sacredness': '[ˈseɪkrɪdnɪs]', 'sacrifice': '[ˈsækrɪˌfaɪs]',
    'sacrificed': '[ˈsækrɪˌfaɪst]', 'sacrificer': '[ˈsækrɪˌfaɪsɚ]', 'sacrifices': '[ˈsækrɪˌfaɪsɪz]', 'sacrificial': '[ˌsækrɪˈfɪʃəl]', 'sacrificially': '[ˌsækrɪˈfɪʃəli]',
    'sacrificing': '[ˈsækrɪˌfaɪsɪŋ]', 'sacrilege': '[ˈsækrɪˌlɪdʒ]', 'sacrileges': '[ˈsækrɪˌlɪdʒɪz]', 'sacrilegious': '[ˌsækrɪˈlɪdʒəs]', 'sacrilegiously': '[ˌsækrɪˈlɪdʒəsli]',
    'sacrilegiousness': '[ˌsækrɪˈlɪdʒəsnɪs]', 'sacrist': '[ˈsækrɪst]', 'sacristan': '[ˈsækrɪstən]', 'sacristans': '[ˈsækrɪstənz]', 'sacristy': '[ˈsækrɪsti]',
    'sacroacral': '[ˌseɪkroʊˈeɪkrəl]', 'sacrociatic': '[ˌseɪkroʊsiˈætɪk]', 'sacrococcygeal': '[ˌseɪkroʊkɑkˈsɪdʒiəl]', 'sacrococcygeus': '[ˌseɪkroʊkɑkˈsɪdʒiəs]', 'sacrodynia': '[ˌseɪkroʊˈdɪniə]',
    'sacroiliitis': '[ˌseɪkroʊɪˌliˈaɪtɪs]', 'sacroiliac': '[ˌseɪkroʊɪˈliæk]', 'sacrospinal': '[ˌseɪkroʊˈspaɪnəl]', 'sacrospinalis': '[ˌseɪkroʊspaɪˈneɪlɪs]', 'sacrosanct': '[ˌsækroʊˈsæŋkt]',
    'sacrosanctity': '[ˌsækroʊsæŋkˈtɪti]', 'sacrosanctly': '[ˌsækroʊˈsæŋktli]', 'sacrosanctness': '[ˌsækroʊˈsæŋktnɪs]', 'sacrum': '[ˈseɪkrəm]', 'sad': '[sæd]',
    'sadden': '[ˈsædən]', 'saddened': '[ˈsædənd]', 'saddening': '[ˈsædənɪŋ]', 'saddenly': '[ˈsædənli]', 'sadder': '[ˈsædɚ]',
    'saddest': '[ˈsædɪst]', 'saddle': '[ˈsædəl]', 'saddlebag': '[ˈsædəlˌbæɡ]', 'saddlebow': '[ˈsædəlˌboʊ]', 'saddlecloth': '[ˈsædəlˌklɔθ]',
    'saddled': '[ˈsædəld]', 'saddler': '[ˈsædlɚ]', 'saddleries': '[ˈsædlərɪz]', 'saddlery': '[ˈsædləri]', 'saddles': '[ˈsædəlz]',
    'saddling': '[ˈsædəlɪŋ]', 'sadly': '[ˈsædli]', 'sadness': '[ˈsædnɪs]', 'sadomasochism': '[ˌseɪdoʊˈmæsəˌkɪzəm]', 'sadomasochist': '[ˌseɪdoʊˈmæsəˌkɪst]',
    'sadomasochistic': '[ˌseɪdoʊˌmæsəˈkɪstɪk]', 'sadomasochistically': '[ˌseɪdoʊˌmæsəˈkɪstɪkəli]', 'sadomasochists': '[ˌseɪdoʊˈmæsəˌkɪsts]', 'sae': '[seɪ]', 'safari': '[səˈfɑri]',
    'safaris': '[səˈfɑriz]', 'safe': '[seɪf]', 'safed': '[ˈseɪfɪd]', 'safeguard': '[ˈseɪfˌɡɑrd]', 'safeguarded': '[ˈseɪfˌɡɑrdɪd]',
    'safeguarding': '[ˈseɪfˌɡɑrdɪŋ]', 'safeguards': '[ˈseɪfˌɡɑrdz]', 'safely': '[ˈseɪfli]', 'safeness': '[ˈseɪfnɪs]', 'safer': '[ˈseɪfɚ]',
    'safest': '[ˈseɪfɪst]', 'safetied': '[ˈseɪfətid]', 'safeties': '[ˈseɪfətiz]', 'safety': '[ˈseɪfti]', 'saffron': '[ˈsæfrən]',
    'sag': '[sæɡ]', 'saga': '[ˈsɑɡə]', 'sagacious': '[səˈɡeɪʃəs]', 'sagaciously': '[səˈɡeɪʃəsli]', 'sagaciousness': '[səˈɡeɪʃəsnɪs]',
    'sagacity': '[səˈɡæsɪti]', 'sagamore': '[ˈsæɡəˌmɔr]', 'sagas': '[ˈsɑɡəz]', 'sage': '[seɪdʒ]', 'sagely': '[ˈseɪdʒli]',
    'sageness': '[ˈseɪdʒnɪs]', 'sager': '[ˈseɪdʒɚ]', 'sages': '[ˈseɪdʒɪz]', 'sagest': '[ˈseɪdʒɪst]', 'saggar': '[ˈsæɡɚ]',
    'saggars': '[ˈsæɡɚz]', 'sagged': '[sæɡd]', 'sagger': '[ˈsæɡɚ]', 'saggers': '[ˈsæɡɚz]', 'sagging': '[ˈsæɡɪŋ]',
    'saggings': '[ˈsæɡɪŋz]', 'saggy': '[ˈsæɡi]', 'sagittal': '[ˈsædʒɪtəl]', 'sagittally': '[ˈsædʒɪtəli]', 'sagittaries': '[ˈsædʒɪˌtɛriz]',
    'sagittarius': '[ˌsædʒɪˈtɛriəs]', 'sagittary': '[ˈsædʒɪˌtɛri]', 'sago': '[ˈseɪɡoʊ]', 'sagos': '[ˈseɪɡoʊz]', 'sagum': '[ˈseɪɡəm]',
    'sagum': '[ˈseɪɡəm]', 'saguaro': '[səˈɡwɑroʊ]', 'saguaros': '[səˈɡwɑroʊz]', 'sahib': '[ˈsɑib]', 'sahibs': '[ˈsɑibz]',
}

wb = openpyxl.load_workbook('2000voc.xlsx')
ws = wb.active
count = 0
for row in range(2, ws.max_row + 1):
    word = ws[f'A{row}'].value
    if word and word.lower() in qz_vocab and not ws[f'B{row}'].value:
        ws[f'B{row}'] = qz_vocab[word.lower()]
        count += 1

wb.save('2000voc.xlsx')
print(f'Batch 7: {count} Q-S words with phonetics added')
