import openpyxl

tz_vocab = {
    # T words
    'table': '[ˈteɪbəl]', 'tablespoon': '[ˈteɪbəlˌspun]', 'tablet': '[ˈtæblɪt]', 'tabloid': '[ˈtæbˌlɔɪd]', 'taboo': '[təˈbu]',
    'tabular': '[ˈtæbjələr]', 'tabulate': '[ˈtæbjəˌleɪt]', 'tabulation': '[ˌtæbjəˈleɪʃən]', 'tack': '[tæk]', 'tackle': '[ˈtækəl]',
    'tacit': '[ˈtæsɪt]', 'tacitly': '[ˈtæsɪtli]', 'tacitness': '[ˈtæsɪtnɪs]', 'taciturn': '[ˈtæsɪˌtɜrn]', 'taciturnity': '[ˌtæsɪˈtɜrnɪti]',
    'tack': '[tæk]', 'tacked': '[tækt]', 'tacking': '[ˈtækɪŋ]', 'tackiness': '[ˈtækinɪs]', 'tackle': '[ˈtækəl]',
    'tackled': '[ˈtækəld]', 'tackler': '[ˈtæklɚ]', 'tackles': '[ˈtækəlz]', 'tackling': '[ˈtæklɪŋ]', 'tacky': '[ˈtæki]',
    'taco': '[ˈtɑkoʊ]', 'tacos': '[ˈtɑkoʊz]', 'tact': '[tækt]', 'tactful': '[ˈtæktfəl]', 'tactfully': '[ˈtæktfəli]',
    'tactfulness': '[ˈtæktfəlnɪs]', 'tactic': '[ˈtæktɪk]', 'tactical': '[ˈtæktɪkəl]', 'tactically': '[ˈtæktɪkəli]', 'tactician': '[tækˈtɪʃən]',
    'tactics': '[ˈtæktɪks]', 'tactile': '[ˈtæktəl]', 'tactilely': '[ˈtæktəli]', 'tactility': '[tækˈtɪləti]', 'tactless': '[ˈtæktlɪs]',
    'tactlessly': '[ˈtæktlɪsli]', 'tactlessness': '[ˈtæktlɪsnɪs]', 'tactual': '[ˈtæktʃuəl]', 'tactually': '[ˈtæktʃuəli]', 'tactus': '[ˈtæktəs]',
    'tactus': '[ˈtæktəs]', 'tadpole': '[ˈtædˌpoʊl]', 'tae': '[teɪ]', 'tael': '[teɪl]', 'taffeta': '[ˈtæfɪtə]',
    'taffetize': '[ˈtæfɪtaɪz]', 'taffeties': '[ˈtæfətiz]', 'taffety': '[ˈtæfɪti]', 'taffia': '[ˈtæfiə]', 'taffias': '[ˈtæfiəz]',
    'taffrail': '[ˈtæfrəl]', 'taffy': '[ˈtæfi]', 'taft': '[tæft]', 'tag': '[tæɡ]', 'tagalism': '[ˈtæɡəˌlɪzəm]',
    'tagalog': '[tæɡəˈlɔɡ]', 'tagamet': '[ˈtæɡəˌmɛt]', 'tagboard': '[ˈtæɡˌbɔrd]', 'tageme': '[ˈtæɡim]', 'tagemic': '[tæɡˈɛmɪk]',
    'tagement': '[ˈtæɡmənt]', 'tagetes': '[tæˈdʒitiz]', 'tagg': '[tæɡ]', 'tagged': '[tæɡd]', 'tagger': '[ˈtæɡɚ]',
    'tagging': '[ˈtæɡɪŋ]', 'taggy': '[ˈtæɡi]', 'taggy': '[ˈtæɡi]', 'taging': '[ˈteɪdʒɪŋ]', 'tagless': '[ˈtæɡlɪs]',
    'tagline': '[ˈtæɡˌlaɪn]', 'tagma': '[ˈtæɡmə]', 'tagmata': '[tæɡˈmeɪtə]', 'tagmeme': '[ˈtæɡˌmim]', 'tagmemic': '[tæɡˈmɛmɪk]',
    'tagmemically': '[tæɡˈmɛmɪkəli]', 'tagmemicist': '[ˌtæɡməˈmɪsɪst]', 'tagmemics': '[tæɡˈmɛmɪks]', 'tagmemist': '[tæɡˈmimɪst]', 'tagmemists': '[tæɡˈmimɪsts]',
    'tagmeme': '[ˈtæɡˌmim]', 'tagmemise': '[ˈtæɡməˌmaɪz]', 'tagmemize': '[ˈtæɡməˌmaɪz]', 'tagmemic': '[tæɡˈmɛmɪk]', 'tagmemically': '[tæɡˈmɛmɪkəli]',
    'tagmemicist': '[ˌtæɡməˈmɪsɪst]', 'tagmemics': '[tæɡˈmɛmɪks]', 'tagmemist': '[tæɡˈmimɪst]', 'tagmemists': '[tæɡˈmimɪsts]', 'tagmemize': '[ˈtæɡməˌmaɪz]',
    'tagmemizing': '[ˈtæɡməˌmaɪzɪŋ]', 'tagmemic': '[tæɡˈmɛmɪk]', 'tagmemically': '[tæɡˈmɛmɪkəli]', 'tagmemicist': '[ˌtæɡməˈmɪsɪst]', 'tagmemics': '[tæɡˈmɛmɪks]',
    'tagmemist': '[tæɡˈmimɪst]', 'tagmemists': '[tæɡˈmimɪsts]', 'tagmemize': '[ˈtæɡməˌmaɪz]', 'tagmemizing': '[ˈtæɡməˌmaɪzɪŋ]', 'tags': '[tæɡz]',
    'taguan': '[ˈtæɡwən]', 'tahini': '[tɑˈhini]', 'tahr': '[tɑr]', 'tahrs': '[tɑrz]', 'tahsil': '[ˈtæsɪl]',
    'tahsildar': '[tæsɪlˈdɑr]', 'tahsildars': '[tæsɪlˈdɑrz]', 'tahsils': '[ˈtæsɪlz]', 'tahuna': '[ˈtɑˌhunə]', 'taias': '[ˈtaɪəz]',
    'tail': '[teɪl]', 'tailback': '[ˈteɪlˌbæk]', 'tailboard': '[ˈteɪlˌbɔrd]', 'tailbone': '[ˈteɪlˌboʊn]', 'tailed': '[teɪld]',
    'tailer': '[ˈteɪlɚ]', 'tailered': '[ˈteɪlərd]', 'tailfin': '[ˈteɪlˌfɪn]', 'tailfins': '[ˈteɪlˌfɪnz]', 'tailgate': '[ˈteɪlˌɡeɪt]',
    'tailgated': '[ˈteɪlˌɡeɪtɪd]', 'tailgater': '[ˈteɪlˌɡeɪtɚ]', 'tailgaters': '[ˈteɪlˌɡeɪtɚz]', 'tailgates': '[ˈteɪlˌɡeɪts]', 'tailgating': '[ˈteɪlˌɡeɪtɪŋ]',
    'tailings': '[ˈteɪlɪŋz]', 'taillamp': '[ˈteɪlˌlæmp]', 'taille': '[ˈtæj]', 'tailless': '[ˈteɪllɪs]', 'taillessness': '[ˈteɪllɪsnɪs]',
    'taillight': '[ˈteɪlˌlaɪt]', 'taillights': '[ˈteɪlˌlaɪts]', 'taillike': '[ˈteɪlˌlaɪk]', 'tailor': '[ˈteɪlɚ]', 'tailored': '[ˈteɪlərd]',
    'tailoring': '[ˈteɪlərɪŋ]', 'tailors': '[ˈteɪlɚz]', 'tailpiece': '[ˈteɪlˌpis]', 'tailpieces': '[ˈteɪlˌpisɪz]', 'tailpipe': '[ˈteɪlˌpaɪp]',
    'tailpipes': '[ˈteɪlˌpaɪps]', 'tailskin': '[ˈteɪlˌskɪn]', 'tailskinner': '[ˈteɪlˌskɪnɚ]', 'tailskinners': '[ˈteɪlˌskɪnɚz]', 'tailskins': '[ˈteɪlˌskɪnz]',
    'tailspin': '[ˈteɪlˌspɪn]', 'tailspins': '[ˈteɪlˌspɪnz]', 'tailstock': '[ˈteɪlˌstɑk]', 'tailstocks': '[ˈteɪlˌstɑks]', 'tailwater': '[ˈteɪlˌwɔtɚ]',
    'tain': '[teɪn]', 'tain': '[teɪn]', 'taint': '[teɪnt]', 'tainted': '[ˈteɪntɪd]', 'taintedly': '[ˈteɪntɪdli]',
    'taintedly': '[ˈteɪntɪdli]', 'taintedness': '[ˈteɪntɪdnɪs]', 'tainter': '[ˈteɪntɚ]', 'taintest': '[ˈteɪntɪst]', 'tainting': '[ˈteɪntɪŋ]',
    'taintingly': '[ˈteɪntɪŋli]', 'taintings': '[ˈteɪntɪŋz]', 'taintless': '[ˈteɪntlɪs]', 'taintlessly': '[ˈteɪntlɪsli]', 'taintlessness': '[ˈteɪntlɪsnɪs]',
    'taints': '[teɪnts]', 'taipo': '[ˈtaɪˌpoʊ]', 'taipos': '[ˈtaɪˌpoʊz]', 'tahr': '[tɑr]', 'tahrs': '[tɑrz]',
    'taj': '[tɑʒ]', 'tajacu': '[ˌtɑhəˈku]', 'tajik': '[ˈtɑdʒɪk]', 'tajiks': '[ˈtɑdʒɪks]', 'tajine': '[tɑˈʒin]',
    'tajines': '[tɑˈʒinz]', 'tajines': '[tɑˈʒinz]', 'tajmahal': '[ˌtɑdʒ mɑˈhɑl]', 'tajoin': '[ˈtaɪˌdʒɔɪn]', 'tajoins': '[ˈtaɪˌdʒɔɪnz]',
    'tajweed': '[ˈtɑdʒˌwid]', 'taka': '[ˈtɑkə]', 'takahe': '[ˈtɑkəˌhi]', 'takahes': '[ˈtɑkəˌhiz]', 'takaka': '[ˈtɑˌkɑkə]',
    'takakas': '[ˈtɑˌkɑkəz]', 'takakis': '[ˈtɑkəhiz]', 'takamaka': '[ˌtɑkəˈmɑkə]', 'takamakas': '[ˌtɑkəˈmɑkəz]', 'takapout': '[ˈtɑkəˌpaʊt]',
    'takapouts': '[ˈtɑkəˌpaʊts]', 'takas': '[ˈtɑkəz]', 'takatahe': '[ˈtɑkətəˌhi]', 'takatable': '[ˈteɪkətəbəl]', 'take': '[teɪk]',
    'takeaway': '[ˈteɪkəˌweɪ]', 'takeaways': '[ˈteɪkəˌweɪz]', 'takedown': '[ˈteɪkˌdaʊn]', 'takedowns': '[ˈteɪkˌdaʊnz]', 'taken': '[ˈteɪkən]',
    'takeoff': '[ˈteɪkˌɔf]', 'takeoffs': '[ˈteɪkˌɔfs]', 'takeout': '[ˈteɪkˌaʊt]', 'takeouts': '[ˈteɪkˌaʊts]', 'takeover': '[ˈteɪkˌoʊvɚ]',
    'takeovers': '[ˈteɪkˌoʊvɚz]', 'taker': '[ˈteɪkɚ]', 'takers': '[ˈteɪkɚz]', 'takes': '[teɪks]', 'takeuchi': '[ˈtɑˌkeɪːtʃi]',
    'taking': '[ˈteɪkɪŋ]', 'takingly': '[ˈteɪkɪŋli]', 'takingness': '[ˈteɪkɪŋnɪs]', 'takings': '[ˈteɪkɪŋz]', 'taks': '[tæks]',
    'takt': '[tɑkt]', 'taktalar': '[ˈtɑktɑlɑr]', 'takulu': '[ˈtɑkuˌlu]', 'tala': '[ˈtɑlə]', 'talao': '[ˈtɑˌlaʊ]',
    'talaria': '[tæˈlɛriə]', 'talaris': '[tæˈlɛrɪs]', 'talaric': '[tæˈlɛrɪk]', 'talarious': '[tæˈlɛriəs]', 'talars': '[ˈtɑlɑrz]',
    'talayotic': '[ˌtæləˈjɑtɪk]', 'talayot': '[ˈtæləˌjɑt]', 'talayots': '[ˈtæləˌjɑts]', 'talbe': '[ˈtælbi]', 'talbes': '[ˈtælbiz]',
    'talbot': '[ˈtælbət]', 'talcose': '[ˈtælˌkoʊs]', 'talcous': '[ˈtælkəs]', 'talc': '[tælk]', 'talced': '[ˈtælkt]',
    'talcing': '[ˈtælkɪŋ]', 'talck': '[tælk]', 'talcked': '[ˈtælkt]', 'talcker': '[ˈtælkɚ]', 'talcking': '[ˈtælkɪŋ]',
    'talcky': '[ˈtælki]', 'talcocele': '[ˈtælkoʊˌsil]', 'talcophile': '[ˈtælkoʊˌfaɪl]', 'talcophilic': '[ˌtælkoʊˈfɪlɪk]', 'talcose': '[ˈtælˌkoʊs]',
    'talcous': '[ˈtælkəs]', 'talcs': '[tælks]', 'talcy': '[ˈtælki]', 'talcum': '[ˈtælkəm]', 'talcums': '[ˈtælkəmz]',
    'tald': '[tɔld]', 'tale': '[teɪl]', 'talebearer': '[ˈteɪlˌbɛrɚ]', 'talebearers': '[ˈteɪlˌbɛrɚz]', 'talebearing': '[ˈteɪlˌbɛrɪŋ]',
    'talebeams': '[ˈteɪlˌbimz]', 'talebearer': '[ˈteɪlˌbɛrɚ]', 'talebearers': '[ˈteɪlˌbɛrɚz]', 'talebearing': '[ˈteɪlˌbɛrɪŋ]', 'talebearings': '[ˈteɪlˌbɛrɪŋz]',
    'talebearingly': '[ˈteɪlˌbɛrɪŋli]', 'talebearness': '[ˈteɪlˌbɛrnɪs]', 'taleful': '[ˈteɪlfəl]', 'talefully': '[ˈteɪlfəli]', 'talelessness': '[ˈteɪllɪsnɪs]',
    'talelessly': '[ˈteɪllɪsli]', 'talemonger': '[ˈteɪlˌmɑŋɡɚ]', 'talemongering': '[ˈteɪlˌmɑŋɡərɪŋ]', 'talemongers': '[ˈteɪlˌmɑŋɡɚz]', 'talenay': '[ˈtælinei]',
    'talency': '[ˈtælinsi]', 'talent': '[ˈtælənt]', 'talents': '[ˈtælənt]', 'taler': '[ˈtɑlɚ]', 'talers': '[ˈtɑlɚz]',
    'tales': '[teɪlz]', 'talesman': '[ˈteɪlzmən]', 'talesmen': '[ˈteɪlzmən]', 'talesor': '[ˈteɪlzɔr]', 'talesorry': '[ˈteɪlzɔri]',
    'talesvara': '[ˈteɪlzˌvɛrə]', 'taleteller': '[ˈteɪlˌtɛlɚ]', 'taletellers': '[ˈteɪlˌtɛlɚz]', 'taletelling': '[ˈteɪlˌtɛlɪŋ]', 'taletellings': '[ˈteɪlˌtɛlɪŋz]',
    # U words
    'ugly': '[ˈʌɡli]', 'uglier': '[ˈʌɡliɚ]', 'ugliest': '[ˈʌɡliɪst]', 'ugliness': '[ˈʌɡlinɪs]', 'ugsome': '[ˈʌɡsəm]',
    'ultilitarian': '[ˌʌtɪˈtɛriən]', 'ultimate': '[ˈʌltɪmɪt]', 'ultimately': '[ˈʌltɪmɪtli]', 'ultimata': '[ʌltɪˈmeɪtə]', 'ultimatum': '[ʌltɪˈmeɪtəm]',
    'ululate': '[ˈʌljəˌleɪt]', 'ululated': '[ˈʌljəˌleɪtɪd]', 'ululateningly': '[ˈʌljəˌleɪtɪŋli]', 'ululatingily': '[ˈʌljəˌleɪtɪŋli]', 'ululatingly': '[ˈʌljəˌleɪtɪŋli]',
    'ululation': '[ˌʌljəˈleɪʃən]', 'ululi': '[ˈuluːliː]', 'ululing': '[ˈʌljəlɪŋ]', 'ululing': '[ˈʌljəlɪŋ]', 'ulva': '[ˈʌlvə]',
    'ulvas': '[ˈʌlvəz]', 'ulva': '[ˈʌlvə]', 'ulus': '[ˈuluːs]', 'umen': '[ˈuːmən]', 'umiak': '[ˈumɪæk]',
    'umiack': '[ˈumɪæk]', 'umiaks': '[ˈumɪæks]', 'umiak': '[ˈumɪæk]', 'umiax': '[ˈumɪæks]', 'umidities': '[juˈmɪdɪtiz]',
    'umidity': '[juˈmɪdɪti]', 'umiety': '[ˈumɪti]', 'umiacks': '[ˈumɪæks]', 'umiacs': '[ˈumɪæks]', 'umimun': '[ˈumɪmən]',
    'umimune': '[ˈumɪmun]', 'umimunity': '[ˌumɪˈmunɪti]', 'umiparity': '[ˌumɪˈpærɪti]', 'umiparous': '[ˈumɪpərəs]', 'umipede': '[ˈumɪˌpid]',
    'umipedes': '[ˈumɪˌpidz]', 'umipedium': '[ˌumɪˈpidiəm]', 'umipes': '[ˈumɪˌpiz]', 'umipesced': '[ˌumɪˈpɛskt]', 'umlauted': '[ˈumˌlaʊtɪd]',
    'umlaut': '[ˈumˌlaʊt]', 'umlaute': '[ˈumˌlaʊt]', 'umlauted': '[ˈumˌlaʊtɪd]', 'umlauting': '[ˈumˌlaʊtɪŋ]', 'umlautings': '[ˈumˌlaʊtɪŋz]',
    'umlauts': '[ˈumˌlaʊts]', 'ummage': '[ˈʌmɪdʒ]', 'umma': '[ˈʊmə]', 'ummah': '[ˈʊmə]', 'ummahs': '[ˈʊməz]',
    'ummas': '[ˈʊməz]', 'ummed': '[ʌmd]', 'ummian': '[ˈʊmiən]', 'ummied': '[ˈʌmid]', 'ummier': '[ˈʌmiɚ]',
    'ummiest': '[ˈʌmiɪst]', 'umming': '[ˈʌmɪŋ]', 'ummingly': '[ˈʌmɪŋli]', 'ummings': '[ˈʌmɪŋz]', 'ummy': '[ˈʌmi]',
    'umm': '[ʌm]', 'ume': '[ˈuːmeɪ]', 'umeboshi': '[ˌuːmeɪˈboʊʃi]', 'umeboshis': '[ˌuːmeɪˈboʊʃiz]', 'umed': '[ˈuːmd]',
    'umeing': '[ˈuːmiŋ]', 'umen': '[ˈuːmən]', 'umentaceous': '[ˌuːmənˈteɪʃəs]', 'umenial': '[ˌuːˈminiəl]', 'umels': '[ˈuːmɛlz]',
    'umen': '[ˈuːmən]', 'umene': '[ˈuːmiːn]', 'umenes': '[ˈuːmiːnz]', 'umenial': '[ˌuːˈminiəl]', 'umenials': '[ˌuːˈminiəlz]',
    'umenous': '[ˈuːmənəs]', 'ument': '[ˈuːment]', 'umentas': '[ˈuːmentəz]', 'umenteals': '[ˈuːmenˌtilz]', 'umentia': '[juːˈmentiə]',
    'umentism': '[ˈuːmentɪzəm]', 'umentum': '[ˈuːmentəm]', 'umentums': '[ˈuːmentəmz]', 'umenuses': '[ˈuːmənəsɪz]', 'umen': '[ˈuːmən]',
    'umeons': '[ˈuːmiːənz]', 'umes': '[ˈuːmz]', 'umesies': '[ˈuːmiːziz]', 'umest': '[ˈuːmɪst]', 'umestag': '[ˈuːmɪstæɡ]',
    'umestags': '[ˈuːmɪstæɡz]', 'umeus': '[ˈuːmiːəs]', 'umen': '[ˈuːmən]', 'umia': '[ˈuːmiə]', 'umiah': '[ˈuːmiə]',
    'umiahs': '[ˈuːmiəz]', 'umian': '[ˈuːmiən]', 'umians': '[ˈuːmiənz]', 'umias': '[ˈuːmiəz]', 'umiauch': '[ˈuːmiːˌɑtʃ]',
    'umiac': '[ˈuːmiæk]', 'umiack': '[ˈuːmiæk]', 'umiacs': '[ˈuːmiæks]', 'umiah': '[ˈuːmiə]', 'umiahs': '[ˈuːmiəz]',
    'umiak': '[ˈuːmiæk]', 'umiaks': '[ˈuːmiæks]', 'umiax': '[ˈuːmiæks]', 'umen': '[ˈuːmən]', 'umenor': '[ˈuːmenɔr]',
    # V words
    'vacant': '[ˈveɪkənt]', 'vacancy': '[ˈveɪkənsi]', 'vacantly': '[ˈveɪkəntli]', 'vacantness': '[ˈveɪkəntnɪs]', 'vacate': '[veɪˈkeɪt]',
    'vacated': '[veɪˈkeɪtɪd]', 'vacates': '[veɪˈkeɪts]', 'vacating': '[veɪˈkeɪtɪŋ]', 'vacation': '[veɪˈkeɪʃən]', 'vacationed': '[veɪˈkeɪʃənd]',
    'vacationing': '[veɪˈkeɪʃənɪŋ]', 'vacationist': '[veɪˈkeɪʃənɪst]', 'vacationists': '[veɪˈkeɪʃənɪsts]', 'vacations': '[veɪˈkeɪʃənz]', 'vaccina': '[vækˈsinə]',
    'vaccinal': '[vækˈsɪnəl]', 'vaccinate': '[ˈvæksɪˌneɪt]', 'vaccinated': '[ˈvæksɪˌneɪtɪd]', 'vaccinates': '[ˈvæksɪˌneɪts]', 'vaccinating': '[ˈvæksɪˌneɪtɪŋ]',
    'vaccination': '[ˌvæksɪˈneɪʃən]', 'vaccinations': '[ˌvæksɪˈneɪʃənz]', 'vaccinator': '[ˈvæksɪˌneɪtɚ]', 'vaccinators': '[ˈvæksɪˌneɪtɚz]', 'vaccine': '[ˈvæksin]',
    'vaccines': '[ˈvæksɪnz]', 'vaccinella': '[ˌvæksɪˈnɛlə]', 'vaccinellae': '[ˌvæksɪˈnɛli]', 'vaccinella': '[ˌvæksɪˈnɛlə]', 'vaccinellas': '[ˌvæksɪˈnɛləz]',
    'vaccinial': '[vækˈsɪniəl]', 'vaccinical': '[vækˈsɪnɪkəl]', 'vaccinically': '[vækˈsɪnɪkəli]', 'vaccinical': '[vækˈsɪnɪkəl]', 'vaccinism': '[ˈvæksɪˌnɪzəm]',
    'vaccinist': '[ˈvæksɪnɪst]', 'vaccinists': '[ˈvæksɪnɪsts]', 'vaccinitic': '[ˌvæksɪˈnɪtɪk]', 'vaccinitis': '[ˌvæksɪˈnaɪtɪs]', 'vaccinogen': '[ˌvæksɪˈnɑdʒən]',
    'vaccinogens': '[ˌvæksɪˈnɑdʒənz]', 'vaccinogenic': '[ˌvæksɪnoʊˈdʒɛnɪk]', 'vaccinogenicity': '[ˌvæksɪnoʊdʒɪˈnɪsɪti]', 'vaccoid': '[ˈvækoɪd]', 'vaccuities': '[vækˈkjuətiz]',
    'vaccuity': '[vækˈkjuəti]', 'vaccum': '[ˈvækjuəm]', 'vaccuma': '[ˈvækjuːmə]', 'vaccumable': '[ˈvækjuməbəl]', 'vaccumed': '[ˈvækjumd]',
    'vaccumer': '[ˈvækjumɚ]', 'vaccumers': '[ˈvækjumɚz]', 'vaccumeter': '[vækˈjumɪtɚ]', 'vaccumi': '[ˈvækjuːmi]', 'vaccuming': '[ˈvækjumɪŋ]',
    'vaccumingly': '[ˈvækjumɪŋli]', 'vaccumings': '[ˈvækjumɪŋz]', 'vaccumiuous': '[vækˈjuːmiːəs]', 'vaccum': '[ˈvækjuəm]', 'vaccums': '[ˈvækjuəmz]',
    'vaccuper': '[ˈvækjupɚ]', 'vaccuperes': '[ˈvækjupərz]', 'vaccuperous': '[vækˈjuːpərəs]', 'vaccus': '[ˈvækəs]', 'vaccusses': '[ˈvækəsɪz]',
    'vaccuthion': '[ˈvækjuːθiən]', 'vacee': '[vəˈsi]', 'vacees': '[vəˈsiz]', 'vacfel': '[ˈvæksɪl]', 'vacfelsies': '[ˈvæksɪlsiz]',
    'vacfelsins': '[ˈvæksɪlsɪnz]', 'vacfels': '[ˈvæksɪlz]', 'vacfemie': '[ˈvæksɪmi]', 'vacfemies': '[ˈvæksɪmiz]', 'vacfeminon': '[ˈvæksɪmɪnɑn]',
    'vacfemine': '[ˈvæksɪmin]', 'vacfemines': '[ˈvæksɪminz]', 'vacfeminon': '[ˈvæksɪmɪnɑn]', 'vacfeminons': '[ˈvæksɪmɪnɑnz]', 'vacfels': '[ˈvæksɪlz]',
    # W words
    'wack': '[wæk]', 'wacke': '[ˈwɑki]', 'wackes': '[ˈwɑkiz]', 'wacker': '[ˈwækɚ]', 'wackers': '[ˈwækɚz]',
    'wackier': '[ˈwækiɚ]', 'wackiest': '[ˈwækiɪst]', 'wackily': '[ˈwækɪli]', 'wackiness': '[ˈwækinɪs]', 'wack': '[wæk]',
    'wacking': '[ˈwækɪŋ]', 'wackings': '[ˈwækɪŋz]', 'wacks': '[wæks]', 'wacky': '[ˈwæki]', 'wadable': '[ˈwodəbəl]',
    'wadcose': '[ˈwɑdˌkoʊs]', 'wadded': '[ˈwɑdɪd]', 'wadder': '[ˈwɑdɚ]', 'wadders': '[ˈwɑdɚz]', 'waddie': '[ˈwɑdi]',
    'wadding': '[ˈwɑdɪŋ]', 'waddings': '[ˈwɑdɪŋz]', 'waddles': '[ˈwɑdəlz]', 'waddled': '[ˈwɑdəld]', 'waddle': '[ˈwɑdəl]',
    'waddler': '[ˈwɑdlɚ]', 'waddlers': '[ˈwɑdlɚz]', 'waddling': '[ˈwɑdəlɪŋ]', 'waddlingly': '[ˈwɑdəlɪŋli]', 'waddings': '[ˈwɑdɪŋz]',
    'waddly': '[ˈwɑdli]', 'waddy': '[ˈwɑdi]', 'wade': '[weɪd]', 'wadeable': '[ˈweɪdəbəl]', 'waded': '[ˈweɪdɪd]',
    'wader': '[ˈweɪdɚ]', 'waders': '[ˈweɪdɚz]', 'wades': '[weɪdz]', 'wadi': '[ˈwɑdi]', 'wadies': '[ˈwɑdiz]',
    'wading': '[ˈweɪdɪŋ]', 'wadings': '[ˈweɪdɪŋz]', 'wadis': '[ˈwɑdiz]', 'wadmaal': '[ˈwɑdˌmɑl]', 'wadmels': '[ˈwɑdˌmɛlz]',
    'wadmol': '[ˈwɑdˌmɔl]', 'wadmoll': '[ˈwɑdˌmɔl]', 'wadmolls': '[ˈwɑdˌmɔlz]', 'wadmols': '[ˈwɑdˌmɔlz]', 'wadset': '[ˈwɑdˌsɛt]',
    'wadsets': '[ˈwɑdˌsɛts]', 'waeg': '[weɪdʒ]', 'waeness': '[ˈwi.nɪs]', 'waes': '[weɪdʒ]', 'wafer': '[ˈweɪfɚ]',
    # X words
    'xanadu': '[ˈzænəˌdu]', 'xanadu': '[ˈzænəˌdu]', 'xanth': '[zænθ]', 'xantha': '[ˈzænθə]', 'xanthan': '[ˈzænθən]',
    'xanthate': '[ˈzænθˌeɪt]', 'xanthates': '[ˈzænθˌeɪts]', 'xanthate': '[ˈzænθˌeɪt]', 'xanthates': '[ˈzænθˌeɪts]', 'xanthen': '[ˈzænθɛn]',
    'xanthene': '[ˈzænθˌin]', 'xanthenes': '[ˈzænθˌinz]', 'xantheno': '[zænˈθiːnoʊ]', 'xanthenol': '[zænˈθɛnɔl]', 'xanthenols': '[zænˈθɛnɔlz]',
    'xanthic': '[ˈzænθɪk]', 'xanthid': '[ˈzænθɪd]', 'xanthic': '[ˈzænθɪk]', 'xanthide': '[ˈzænθɪd]', 'xanthidic': '[ˌzænθɪˈdɪk]',
    'xanthin': '[ˈzænθɪn]', 'xanthina': '[zænˈθiːnə]', 'xanthinal': '[zænˈθiːnəl]', 'xanthine': '[ˈzænθin]', 'xanthines': '[ˈzænθinz]',
    'xanthins': '[ˈzænθɪnz]', 'xanthio': '[ˈzænθioʊ]', 'xanthioid': '[ˌzænθiˈɔɪd]', 'xanthioids': '[ˌzænθiˈɔɪdz]', 'xanthion': '[ˈzænθiən]',
    'xanthium': '[ˈzænθiəm]', 'xanthium': '[ˈzænθiəm]', 'xanthiums': '[ˈzænθiəmz]', 'xanthoderm': '[ˈzænθoʊˌdɜrm]', 'xanths': '[zænθs]',
    # Y words
    'yacht': '[jɑt]', 'yachted': '[ˈjɑtɪd]', 'yachter': '[ˈjɑtɚ]', 'yachters': '[ˈjɑtɚz]', 'yachting': '[ˈjɑtɪŋ]',
    'yachtings': '[ˈjɑtɪŋz]', 'yachtless': '[ˈjɑtlɪs]', 'yachtman': '[ˈjɑtmən]', 'yachtmen': '[ˈjɑtmən]', 'yachtmer': '[ˈjɑtmɛr]',
    'yachtmers': '[ˈjɑtmɛrz]', 'yachtmestress': '[ˈjɑtmɪstrɪs]', 'yachtmistress': '[ˈjɑtmɪstrɪs]', 'yachtmistresses': '[ˈjɑtmɪstrɪsɪz]', 'yachtowners': '[ˈjɑtˌoʊnɚz]',
    'yachtowner': '[ˈjɑtˌoʊnɚ]', 'yachtownership': '[ˈjɑtˌoʊnɚʃɪp]', 'yachtpole': '[ˈjɑtˌpoʊl]', 'yachtpoles': '[ˈjɑtˌpoʊlz]', 'yachtries': '[ˈjɑtriz]',
    'yachts': '[jɑts]', 'yachtsman': '[ˈjɑtsmən]', 'yachtsmanlike': '[ˈjɑtsmənˌlaɪk]', 'yachtsmanly': '[ˈjɑtsmənli]', 'yachtsmanship': '[ˈjɑtsmənˌʃɪp]',
    'yachtsmen': '[ˈjɑtsmən]', 'yachtswain': '[ˈjɑtˌsweɪn]', 'yachtswains': '[ˈjɑtˌsweɪnz]', 'yachtswomen': '[ˈjɑtsˌwɪmən]', 'yachtwoman': '[ˈjɑtsˌwʊmən]',
    'yachtys': '[ˈjɑtiz]', 'yack': '[jæk]', 'yacked': '[jækt]', 'yacka': '[ˈjækə]', 'yackas': '[ˈjækəz]',
    'yacker': '[ˈjækɚ]', 'yackers': '[ˈjækɚz]', 'yacking': '[ˈjækɪŋ]', 'yacks': '[jæks]', 'yacumama': '[ˌjɑkuːˈmɑmə]',
    'yacumamas': '[ˌjɑkuːˈmɑməz]', 'yad': '[jɑd]', 'yada': '[ˈjɑdə]', 'yadah': '[ˈjɑdə]', 'yadahs': '[ˈjɑdəz]',
    'yadas': '[ˈjɑdəz]', 'yaff': '[jæf]', 'yaffed': '[jæft]', 'yaffer': '[ˈjæfɚ]', 'yaffers': '[ˈjæfɚz]',
    'yaffil': '[ˈjæfɪl]', 'yaffils': '[ˈjæfɪlz]', 'yaffing': '[ˈjæfɪŋ]', 'yaffings': '[ˈjæfɪŋz]', 'yaffles': '[ˈjæfəlz]',
    'yaffle': '[ˈjæfəl]', 'yaffled': '[ˈjæfəld]', 'yaffler': '[ˈjæflɚ]', 'yafflers': '[ˈjæflɚz]', 'yaffling': '[ˈjæfəlɪŋ]',
    'yaffs': '[jæfs]', 'yag': '[jæɡ]', 'yager': '[ˈjeɪɡɚ]', 'yagers': '[ˈjeɪɡɚz]', 'yagi': '[ˈjɑɡi]',
    'yagis': '[ˈjɑɡiz]', 'yags': '[jæɡz]', 'yaguami': '[ˌjæɡwɑˈmi]', 'yaguamis': '[ˌjæɡwɑˈmiz]', 'yaguarete': '[ˌjæɡwɑˈrɛti]',
    'yaguaretes': '[ˌjæɡwɑˈrɛtiz]', 'yaguarundi': '[ˌjæɡwɑˈrʊndi]', 'yaguarundia': '[ˌjæɡwɑˈrʊndiə]', 'yaguarundia': '[ˌjæɡwɑˈrʊndiə]', 'yaguarunundis': '[ˌjæɡwɑˈrʊndiz]',
    'yah': '[jɑ]', 'yaheh': '[ˈjɑi]', 'yahen': '[ˈjɑən]', 'yahes': '[ˈjɑez]', 'yahhweh': '[ˈjɑwə]',
    'yahis': '[ˈjɑiz]', 'yahly': '[ˈjɑli]', 'yahoo': '[jəˈhu]', 'yahoos': '[jəˈhuz]', 'yahshua': '[ˈjɑʃuːə]',
    'yahu': '[ˈjɑhu]', 'yahual': '[ˈjɑwəl]', 'yahuals': '[ˈjɑwəlz]', 'yahve': '[ˈjɑvi]', 'yahvehs': '[ˈjɑviz]',
    'yahve': '[ˈjɑvi]', 'yahveh': '[ˈjɑvə]', 'yahveh': '[ˈjɑvə]', 'yahvehs': '[ˈjɑvəz]', 'yahwe': '[ˈjɑwi]',
    'yahweh': '[ˈjɑwə]', 'yahwehs': '[ˈjɑwəz]', 'yahwes': '[ˈjɑwiz]', 'yahwism': '[ˈjɑwɪzəm]', 'yahwisms': '[ˈjɑwɪzəmz]',
    'yahwist': '[ˈjɑwɪst]', 'yahwistic': '[jɑwˈɪstɪk]', 'yahwistically': '[jɑwˈɪstɪkəli]', 'yahwists': '[ˈjɑwɪsts]', 'yahwistic': '[jɑwˈɪstɪk]',
    # Z words
    'zaire': '[zɑˈir]', 'zaires': '[zɑˈirz]', 'zairean': '[zɑɪˈriən]', 'zaireans': '[zɑɪˈriənz]', 'zak': '[zæk]',
    'zakah': '[zəˈkɑ]', 'zakahs': '[zəˈkɑz]', 'zakat': '[zəˈkɑt]', 'zakats': '[zəˈkɑts]', 'zakuski': '[zɑˈkuskɪ]',
    'zakuskie': '[zɑˈkuskɪ]', 'zakuskis': '[zɑˈkuskiz]', 'zaks': '[zæks]', 'zal': '[zɑl]', 'zalambdodont': '[ˌzælæmˈdɑdɑnt]',
    'zalambdodonts': '[ˌzælæmˈdɑdɑnts]', 'zalambdodontia': '[ˌzælæmˈdɑdɑntiə]', 'zalambdodontism': '[ˌzælæmˈdɑdɑntɪzəm]', 'zalambdodontous': '[ˌzælæmˈdɑdɑntəs]',
    'zalambdodonty': '[ˌzælæmˈdɑdɑnti]', 'zalambdodontism': '[ˌzælæmˈdɑdɑntɪzəm]', 'zalambdodontous': '[ˌzælæmˈdɑdɑntəs]', 'zalambdodont': '[ˌzælæmˈdɑdɑnt]', 'zals': '[zɑlz]',
    'zaltys': '[ˈzɑltiz]', 'zaltis': '[ˈzɑltɪs]', 'zaltys': '[ˈzɑltiz]', 'zamac': '[ˈzæmæk]', 'zamacs': '[ˈzæmæks]',
    'zamang': '[ˈzæməŋ]', 'zamangs': '[ˈzæməŋz]', 'zamarilla': '[ˌzæməˈrɪlə]', 'zamarillas': '[ˌzæməˈrɪləz]', 'zamarilla': '[ˌzæməˈrɪlə]',
    'zamarillo': '[ˌzæməˈrɪloʊ]', 'zamarillos': '[ˌzæməˈrɪloʊz]', 'zamaros': '[ˌzæməˈroʊz]', 'zamarrilla': '[ˌzæməˈrɪlə]', 'zamarrillas': '[ˌzæməˈrɪləz]',
    'zambang': '[ˈzæmbæŋ]', 'zambangs': '[ˈzæmbæŋz]', 'zambes': '[zɑmˈbɛz]', 'zambese': '[zɑmˈbis]', 'zambesi': '[zɑmˈbɛzɪ]',
    'zambesia': '[zɑmˈbɛʒə]', 'zambesial': '[zɑmˈbɛʒəl]', 'zambesian': '[zɑmˈbɛʒən]', 'zambezian': '[zɑmˈbɛziən]', 'zambians': '[zɑmˈbiənz]',
    'zambian': '[ˈzɑmbiən]', 'zambians': '[zɑmˈbiənz]', 'zambos': '[ˈzæmboʊz]', 'zambo': '[ˈzæmboʊ]', 'zamboni': '[zæmˈboʊni]',
    'zambonis': '[zæmˈboʊniz]', 'zambra': '[ˈzæmbrə]', 'zambras': '[ˈzæmbrəz]', 'zambuks': '[ˈzæmbəks]', 'zambuk': '[ˈzæmbək]',
    'zambura': '[zɑmˈbjʊrə]', 'zampogna': '[zæmˈpoʊnjə]', 'zampogne': '[zæmˈpoʊnjə]', 'zampognas': '[zæmˈpoʊnjəz]', 'zampognes': '[zæmˈpoʊnjəz]',
    'zampone': '[zæmˈpoʊni]', 'zampones': '[zæmˈpoʊniz]', 'zampony': '[zæmˈpoʊni]', 'zampoy': '[zæmˈpoɪ]', 'zampoys': '[zæmˈpoɪz]',
    'zampuy': '[zæmˈpoʊi]', 'zampuys': '[zæmˈpoʊiz]', 'zamstruck': '[ˈzæmˌstrʌk]', 'zamstruckly': '[ˈzæmˌstrʌkli]', 'zamsueh': '[ˈzæmˌsuə]',
    'zamtuch': '[ˈzæmtʃutʃ]', 'zamtuchman': '[ˈzæmtʃutʃmən]', 'zamuca': '[ˈzæmjukə]', 'zamucas': '[ˈzæmjukəz]', 'zamuci': '[ˈzæmjusi]',
    'zamudio': '[ˌzæmˈuːdioʊ]', 'zamuldi': '[ˈzæmʊldi]', 'zamunda': '[ˈzæmʊndə]', 'zamundas': '[ˈzæmʊndəz]', 'zamus': '[ˈzæməs]',
    'zamut': '[ˈzæmət]', 'zamuts': '[ˈzæməts]', 'zamza': '[ˈzæmzə]', 'zamzas': '[ˈzæmzəz]', 'zan': '[zæn]',
    'zanas': '[ˈzænəz]', 'zanche': '[ˈzænʃi]', 'zancheas': '[ˈzænʃiəz]', 'zanches': '[ˈzænʃiz]', 'zanchi': '[ˈzænki]',
    'zand': '[zænd]', 'zanda': '[ˈzændə]', 'zandal': '[ˈzændəl]', 'zandale': '[ˈzændɛl]', 'zandale': '[ˈzændɛl]',
    'zandales': '[ˈzændɛliz]', 'zandals': '[ˈzændəlz]', 'zandas': '[ˈzændəz]', 'zandce': '[ˈzændsi]', 'zande': '[ˈzændi]',
    'zandee': '[ˈzændi]', 'zandeis': '[ˈzændeɪz]', 'zandes': '[ˈzændiz]', 'zandi': '[ˈzændi]', 'zandian': '[ˈzændiən]',
    'zandian': '[ˈzændiən]', 'zandians': '[ˈzændiənz]', 'zandic': '[ˈzændɪk]', 'zandies': '[ˈzændiz]', 'zandik': '[ˈzændɪk]',
    'zandika': '[ˌzænˈdikə]', 'zandikas': '[ˌzænˈdikəz]', 'zandikism': '[ˈzændɪkɪzəm]', 'zandikism': '[ˈzændɪkɪzəm]', 'zandiks': '[ˈzændɪks]',
}

wb = openpyxl.load_workbook('2000voc.xlsx')
ws = wb.active
count = 0
for row in range(2, ws.max_row + 1):
    word = ws[f'A{row}'].value
    if word and word.lower() in tz_vocab and not ws[f'B{row}'].value:
        ws[f'B{row}'] = tz_vocab[word.lower()]
        count += 1

wb.save('2000voc.xlsx')
print(f'Batch 8: {count} T-Z words with phonetics added')
